# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.18.0/www/docs/static/schema.json
version: 2

project_name: fallout-terminal

builds:
  - id: preverified-portable-matrix
    skip: true

checksum:
  disable: true

release:
  draft: false
  prerelease: auto
  name_template: 'Fallout Terminal {{ .Tag }}'
  extra_files:
    - glob: ./combined/Fallout-Terminal-windows-amd64.zip
    - glob: ./combined/Fallout-Terminal-windows-arm64.zip
    - glob: ./combined/Fallout-Terminal-linux-amd64.tar.gz
    - glob: ./combined/Fallout-Terminal-linux-arm64.tar.gz
    - glob: ./combined/Fallout-Terminal-darwin-arm64.zip
