// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    CommandApprovalMode,
    CommandExecutionDecision,
    CommandExecutionPhase,
    CommandExecutionPresentation,
    ControllerTerminalPresentation,
    ControllerTerminalPresentationKind,
    FacilityConditionPreview,
    FacilityDependency,
    FacilityDependencyKind,
    FacilityDependencyReport,
    FacilityDeviceStatePreview,
    FacilityEntityKind,
    FacilityEntityReference,
    FacilityFailureCode,
    FacilityIssue,
    FacilityOperationResult,
    HackColumn,
    HackWord,
    MasterBroadcastState,
    MasterCoordinationState,
    MasterPendingCommandExecution,
    MasterPendingSwitch,
    MasterPendingTerminalNavigation,
    MasterRosterEntry,
    MasterSessionEntry,
    MasterTerminalNavigationNotice,
    NavState,
    PendingTerminalNavigationPresentation,
    PlayerCharacter,
    PlayerConfigMetadata,
    PlayerRole,
    PublicHackPattern,
    PublicHackState,
    PublicLiveState,
    ServerInfo,
    TerminalGroup,
    TerminalNavigationDecision,
    TerminalNavigationDirection,
    TerminalNavigationNoticeReason,
    TerminalNavigationPresentation,
    TerminalPresentationEffect,
    TerminalReturnTarget,
    TerminalSwitchChoice
} from "./models.js";

import * as $models from "./models.js";

/**
 * BroadcastID identifies one live-broadcast lifetime.
 * @typedef {$models.BroadcastID} BroadcastID
 */

/**
 * CharacterID identifies one process-local roster entry.
 * @typedef {$models.CharacterID} CharacterID
 */

/**
 * ContentNode is a tagged folder, command, or entry node.
 * @typedef {$models.ContentNode} ContentNode
 */

/**
 * DiagnosticRecoveryReference is one allowlisted recovery variant. Validation
 * requires exactly one pointer to be non-nil.
 * @typedef {$models.DiagnosticRecoveryReference} DiagnosticRecoveryReference
 */

/**
 * LogicalSessionID identifies one browser profile for the lifetime of a server process.
 * @typedef {$models.LogicalSessionID} LogicalSessionID
 */

/**
 * PendingFacilityAction is the detached world-action intent captured during
 * the existing private command approval lifecycle.
 * @typedef {$models.PendingFacilityAction} PendingFacilityAction
 */

/**
 * Session is the durable version-1 campaign document.
 * @typedef {$models.Session} Session
 */

/**
 * SwitchID identifies one pending terminal-switch decision.
 * @typedef {$models.SwitchID} SwitchID
 */
