// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BroadcastID identifies one live-broadcast lifetime.
 * @typedef {string} BroadcastID
 */

/**
 * CharacterID identifies one process-local roster entry.
 * @typedef {string} CharacterID
 */

/**
 * CommandApprovalMode records the exact behavior that will run after the
 * Overseer approves a pending command. Completed state-changing commands
 * remain distinct because approval must show their frozen result without a
 * second durable write.
 * @readonly
 * @enum {string}
 */
export const CommandApprovalMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CommandApprovalModeOrdinary: "ordinary",
    CommandApprovalModeStateChange: "state-change",
    CommandApprovalModeCompletedStateChange: "completed-state-change",
};

/**
 * CommandExecutionDecision is the trusted Overseer resolution for the
 * exact currently pending state-changing command request.
 * @readonly
 * @enum {string}
 */
export const CommandExecutionDecision = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CommandExecutionApprove: "approve",
    CommandExecutionReject: "reject",
};

/**
 * CommandExecutionPhase is the public broadcast-scoped presentation state.
 * @readonly
 * @enum {string}
 */
export const CommandExecutionPhase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CommandExecutionPhasePending: "pending",
    CommandExecutionPhaseRejected: "rejected",
};

/**
 * CommandExecutionPresentation exposes only the shared phase and stable
 * command identity. Master prompt and request identity remain private.
 */
export class CommandExecutionPresentation {
    /**
     * Creates a new CommandExecutionPresentation instance.
     * @param {Partial<CommandExecutionPresentation>} [$$source = {}] - The source object to create the CommandExecutionPresentation.
     */
    constructor($$source = {}) {
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {CommandExecutionPhase}
             */
            this["phase"] = CommandExecutionPhase.$zero;
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandExecutionPresentation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandExecutionPresentation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandExecutionPresentation(/** @type {Partial<CommandExecutionPresentation>} */($$parsedSource));
    }
}

/**
 * ContentNode is a tagged folder, command, or entry node.
 * @typedef {any} ContentNode
 */

/**
 * ControllerTerminalPresentation is the complete semantic selection for one
 * active terminal context. Exactly the fields admitted by Kind may be set.
 */
export class ControllerTerminalPresentation {
    /**
     * Creates a new ControllerTerminalPresentation instance.
     * @param {Partial<ControllerTerminalPresentation>} [$$source = {}] - The source object to create the ControllerTerminalPresentation.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ControllerTerminalPresentationKind}
             */
            this["kind"] = ControllerTerminalPresentationKind.$zero;
        }
        if (!("contextKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contextKey"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["targetId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["patternId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pageIndex"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ControllerTerminalPresentation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ControllerTerminalPresentation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ControllerTerminalPresentation(/** @type {Partial<ControllerTerminalPresentation>} */($$parsedSource));
    }
}

/**
 * ControllerTerminalPresentationKind identifies the stable semantic portion
 * of the terminal view shared by the controller and every observer. Pointer
 * coordinates, DOM focus, viewport geometry, and audio eligibility remain
 * deliberately outside this process-local value.
 * @readonly
 * @enum {string}
 */
export const ControllerTerminalPresentationKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ControllerTerminalPresentationNone: "none",
    ControllerTerminalPresentationMenu: "menu",
    ControllerTerminalPresentationPage: "page",
    ControllerTerminalPresentationHacking: "hacking",
};

/**
 * DiagnosticRecoveryReference is one allowlisted recovery variant. Validation
 * requires exactly one pointer to be non-nil.
 * @typedef {any} DiagnosticRecoveryReference
 */

/**
 * FacilityConditionPreview is a detached condition override used only for
 * projection previews.
 */
export class FacilityConditionPreview {
    /**
     * Creates a new FacilityConditionPreview instance.
     * @param {Partial<FacilityConditionPreview>} [$$source = {}] - The source object to create the FacilityConditionPreview.
     */
    constructor($$source = {}) {
        if (!("ConditionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ConditionID"] = "";
        }
        if (!("Active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacilityConditionPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacilityConditionPreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacilityConditionPreview(/** @type {Partial<FacilityConditionPreview>} */($$parsedSource));
    }
}

/**
 * FacilityDependency identifies one direct reference to a facility entity.
 */
export class FacilityDependency {
    /**
     * Creates a new FacilityDependency instance.
     * @param {Partial<FacilityDependency>} [$$source = {}] - The source object to create the FacilityDependency.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {FacilityDependencyKind}
             */
            this["kind"] = FacilityDependencyKind.$zero;
        }
        if (!("sourceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceId"] = "";
        }
        if (!("targetId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetId"] = "";
        }
        if (!("property" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["property"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["terminalId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacilityDependency instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacilityDependency}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacilityDependency(/** @type {Partial<FacilityDependency>} */($$parsedSource));
    }
}

/**
 * FacilityDependencyKind identifies where one facility reference originates.
 * @readonly
 * @enum {string}
 */
export const FacilityDependencyKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FacilityDependencyKindUnspecified: "unspecified",
    FacilityDependencyKindTransitionPrecondition: "transition-precondition",
    FacilityDependencyKindTransitionConditionEffect: "transition-condition-effect",
    FacilityDependencyKindRecoveryReference: "recovery-reference",
    FacilityDependencyKindRecoveryProgramTransition: "recovery-program-transition",
    FacilityDependencyKindCommandAction: "command-action",
    FacilityDependencyKindNameVariant: "name-variant",
    FacilityDependencyKindEntryContentVariant: "entry-content-variant",
    FacilityDependencyKindVisibility: "visibility",
    FacilityDependencyKindAvailability: "availability",
    FacilityDependencyKindDiagnosticScope: "diagnostic-scope",
    FacilityDependencyKindDiagnosticEffect: "diagnostic-effect",
};

/**
 * FacilityDependencyReport is a detached list of references to one entity.
 */
export class FacilityDependencyReport {
    /**
     * Creates a new FacilityDependencyReport instance.
     * @param {Partial<FacilityDependencyReport>} [$$source = {}] - The source object to create the FacilityDependencyReport.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {FacilityEntityReference}
             */
            this["target"] = (new FacilityEntityReference());
        }
        if (!("dependencies" in $$source)) {
            /**
             * @member
             * @type {FacilityDependency[]}
             */
            this["dependencies"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacilityDependencyReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacilityDependencyReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField0_0($$parsedSource["target"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField1_0($$parsedSource["dependencies"]);
        }
        return new FacilityDependencyReport(/** @type {Partial<FacilityDependencyReport>} */($$parsedSource));
    }
}

/**
 * FacilityDeviceStatePreview is a detached state override used only for
 * projection previews.
 */
export class FacilityDeviceStatePreview {
    /**
     * Creates a new FacilityDeviceStatePreview instance.
     * @param {Partial<FacilityDeviceStatePreview>} [$$source = {}] - The source object to create the FacilityDeviceStatePreview.
     */
    constructor($$source = {}) {
        if (!("DeviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["DeviceID"] = "";
        }
        if (!("StateID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["StateID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacilityDeviceStatePreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacilityDeviceStatePreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacilityDeviceStatePreview(/** @type {Partial<FacilityDeviceStatePreview>} */($$parsedSource));
    }
}

/**
 * FacilityEntityKind identifies a durable entity addressed by dependency
 * inspection and repair.
 * @readonly
 * @enum {string}
 */
export const FacilityEntityKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FacilityEntityKindUnspecified: "unspecified",
    FacilityEntityKindDevice: "device",
    FacilityEntityKindDeviceState: "device-state",
    FacilityEntityKindDeviceTransition: "device-transition",
    FacilityEntityKindCondition: "condition",
    FacilityEntityKindRecoveryProgram: "recovery-program",
};

/**
 * FacilityEntityReference identifies a dependency target. OwnerID qualifies a
 * device-scoped state or transition identity.
 */
export class FacilityEntityReference {
    /**
     * Creates a new FacilityEntityReference instance.
     * @param {Partial<FacilityEntityReference>} [$$source = {}] - The source object to create the FacilityEntityReference.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {FacilityEntityKind}
             */
            this["kind"] = FacilityEntityKind.$zero;
        }
        if (!("entityId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["ownerId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacilityEntityReference instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacilityEntityReference}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacilityEntityReference(/** @type {Partial<FacilityEntityReference>} */($$parsedSource));
    }
}

/**
 * FacilityFailureCode is a stable structured facility operation outcome.
 * @readonly
 * @enum {string}
 */
export const FacilityFailureCode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FacilityFailureUnspecified: "unspecified",
    FacilityFailureRejected: "rejected",
    FacilityFailureMissingReference: "missing-reference",
    FacilityFailureInvalidTransition: "invalid-transition",
    FacilityFailurePreconditionFailed: "precondition-failed",
    FacilityFailureStaleRevision: "stale-revision",
    FacilityFailureConflict: "conflict",
    FacilityFailureDuplicate: "duplicate",
    FacilityFailureInvalidConfiguration: "invalid-configuration",
    FacilityFailurePersistenceFailed: "persistence-failed",
    FacilityFailureRuntimeContextEnded: "runtime-context-ended",
};

/**
 * FacilityIssue identifies one stable configuration or operation failure.
 */
export class FacilityIssue {
    /**
     * Creates a new FacilityIssue instance.
     * @param {Partial<FacilityIssue>} [$$source = {}] - The source object to create the FacilityIssue.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {FacilityFailureCode}
             */
            this["code"] = FacilityFailureCode.$zero;
        }
        if (!("entityKind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityKind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["entityId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["referenceKind"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["referenceId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacilityIssue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacilityIssue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacilityIssue(/** @type {Partial<FacilityIssue>} */($$parsedSource));
    }
}

/**
 * FacilityOperationResult is the detached outcome of one serialized facility
 * mutation attempt.
 */
export class FacilityOperationResult {
    /**
     * Creates a new FacilityOperationResult instance.
     * @param {Partial<FacilityOperationResult>} [$$source = {}] - The source object to create the FacilityOperationResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("changed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["changed"] = false;
        }
        if (!("correlationId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["correlationId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FacilityFailureCode | undefined}
             */
            this["failure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FacilityIssue[] | undefined}
             */
            this["issues"] = undefined;
        }
        if (!("sessionRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionRevision"] = 0;
        }
        if (!("previousFacilityRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["previousFacilityRevision"] = 0;
        }
        if (!("resultingFacilityRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resultingFacilityRevision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["affectedDeviceIds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["affectedConditionIds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Session | null | undefined}
             */
            this["session"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacilityOperationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacilityOperationResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField4_0($$parsedSource["issues"]);
        }
        if ("affectedDeviceIds" in $$parsedSource) {
            $$parsedSource["affectedDeviceIds"] = $$createField8_0($$parsedSource["affectedDeviceIds"]);
        }
        if ("affectedConditionIds" in $$parsedSource) {
            $$parsedSource["affectedConditionIds"] = $$createField9_0($$parsedSource["affectedConditionIds"]);
        }
        return new FacilityOperationResult(/** @type {Partial<FacilityOperationResult>} */($$parsedSource));
    }
}

/**
 * HackColumn is one 192-character public hacking column.
 */
export class HackColumn {
    /**
     * Creates a new HackColumn instance.
     * @param {Partial<HackColumn>} [$$source = {}] - The source object to create the HackColumn.
     */
    constructor($$source = {}) {
        if (!("addresses" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["addresses"] = [];
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("words" in $$source)) {
            /**
             * @member
             * @type {HackWord[]}
             */
            this["words"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HackColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HackColumn}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addresses" in $$parsedSource) {
            $$parsedSource["addresses"] = $$createField0_0($$parsedSource["addresses"]);
        }
        if ("words" in $$parsedSource) {
            $$parsedSource["words"] = $$createField2_0($$parsedSource["words"]);
        }
        return new HackColumn(/** @type {Partial<HackColumn>} */($$parsedSource));
    }
}

/**
 * HackWord describes a visible word placement in a hacking column.
 */
export class HackWord {
    /**
     * Creates a new HackWord instance.
     * @param {Partial<HackWord>} [$$source = {}] - The source object to create the HackWord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["length"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HackWord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HackWord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HackWord(/** @type {Partial<HackWord>} */($$parsedSource));
    }
}

/**
 * LogicalSessionID identifies one browser profile for the lifetime of a server process.
 * @typedef {string} LogicalSessionID
 */

/**
 * MasterBroadcastState is the Overseer view of the current broadcast epoch.
 */
export class MasterBroadcastState {
    /**
     * Creates a new MasterBroadcastState instance.
     * @param {Partial<MasterBroadcastState>} [$$source = {}] - The source object to create the MasterBroadcastState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["id"] = "";
        }
        if (!("controllerSessionId" in $$source)) {
            /**
             * @member
             * @type {LogicalSessionID | null}
             */
            this["controllerSessionId"] = null;
        }
        if (!("activeTerminalId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["activeTerminalId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterBroadcastState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterBroadcastState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterBroadcastState(/** @type {Partial<MasterBroadcastState>} */($$parsedSource));
    }
}

/**
 * MasterCoordinationState is one detached private-desktop projection.
 */
export class MasterCoordinationState {
    /**
     * Creates a new MasterCoordinationState instance.
     * @param {Partial<MasterCoordinationState>} [$$source = {}] - The source object to create the MasterCoordinationState.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["facilityRevision"] = undefined;
        }
        if (!("playerConfig" in $$source)) {
            /**
             * @member
             * @type {PlayerConfigMetadata | null}
             */
            this["playerConfig"] = null;
        }
        if (!("roster" in $$source)) {
            /**
             * @member
             * @type {MasterRosterEntry[]}
             */
            this["roster"] = [];
        }
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {MasterSessionEntry[]}
             */
            this["sessions"] = [];
        }
        if (!("broadcast" in $$source)) {
            /**
             * @member
             * @type {MasterBroadcastState | null}
             */
            this["broadcast"] = null;
        }
        if (!("pendingSwitch" in $$source)) {
            /**
             * @member
             * @type {MasterPendingSwitch | null}
             */
            this["pendingSwitch"] = null;
        }
        if (!("pendingCommandExecution" in $$source)) {
            /**
             * @member
             * @type {MasterPendingCommandExecution | null}
             */
            this["pendingCommandExecution"] = null;
        }
        if (!("pendingTerminalNavigation" in $$source)) {
            /**
             * @member
             * @type {MasterPendingTerminalNavigation | null}
             */
            this["pendingTerminalNavigation"] = null;
        }
        if (!("terminalNavigationNotice" in $$source)) {
            /**
             * @member
             * @type {MasterTerminalNavigationNotice | null}
             */
            this["terminalNavigationNotice"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterCoordinationState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterCoordinationState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType17;
        const $$createField7_0 = $$createType19;
        const $$createField8_0 = $$createType21;
        const $$createField9_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("playerConfig" in $$parsedSource) {
            $$parsedSource["playerConfig"] = $$createField2_0($$parsedSource["playerConfig"]);
        }
        if ("roster" in $$parsedSource) {
            $$parsedSource["roster"] = $$createField3_0($$parsedSource["roster"]);
        }
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField4_0($$parsedSource["sessions"]);
        }
        if ("broadcast" in $$parsedSource) {
            $$parsedSource["broadcast"] = $$createField5_0($$parsedSource["broadcast"]);
        }
        if ("pendingSwitch" in $$parsedSource) {
            $$parsedSource["pendingSwitch"] = $$createField6_0($$parsedSource["pendingSwitch"]);
        }
        if ("pendingCommandExecution" in $$parsedSource) {
            $$parsedSource["pendingCommandExecution"] = $$createField7_0($$parsedSource["pendingCommandExecution"]);
        }
        if ("pendingTerminalNavigation" in $$parsedSource) {
            $$parsedSource["pendingTerminalNavigation"] = $$createField8_0($$parsedSource["pendingTerminalNavigation"]);
        }
        if ("terminalNavigationNotice" in $$parsedSource) {
            $$parsedSource["terminalNavigationNotice"] = $$createField9_0($$parsedSource["terminalNavigationNotice"]);
        }
        return new MasterCoordinationState(/** @type {Partial<MasterCoordinationState>} */($$parsedSource));
    }
}

/**
 * MasterPendingCommandExecution is the complete private prompt projection.
 */
export class MasterPendingCommandExecution {
    /**
     * Creates a new MasterPendingCommandExecution instance.
     * @param {Partial<MasterPendingCommandExecution>} [$$source = {}] - The source object to create the MasterPendingCommandExecution.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("broadcastId" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["broadcastId"] = "";
        }
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }
        if (!("commandName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandName"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {CommandApprovalMode}
             */
            this["mode"] = CommandApprovalMode.$zero;
        }
        if (!("confirmationText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["confirmationText"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PendingFacilityAction | null | undefined}
             */
            this["facilityAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterPendingCommandExecution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterPendingCommandExecution}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterPendingCommandExecution(/** @type {Partial<MasterPendingCommandExecution>} */($$parsedSource));
    }
}

/**
 * MasterPendingSwitch is the non-secret metadata for one pending switch decision.
 */
export class MasterPendingSwitch {
    /**
     * Creates a new MasterPendingSwitch instance.
     * @param {Partial<MasterPendingSwitch>} [$$source = {}] - The source object to create the MasterPendingSwitch.
     */
    constructor($$source = {}) {
        if (!("switchId" in $$source)) {
            /**
             * @member
             * @type {SwitchID}
             */
            this["switchId"] = "";
        }
        if (!("broadcastId" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["broadcastId"] = "";
        }
        if (!("sourceTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalId"] = "";
        }
        if (!("targetTerminalId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["targetTerminalId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterPendingSwitch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterPendingSwitch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterPendingSwitch(/** @type {Partial<MasterPendingSwitch>} */($$parsedSource));
    }
}

export class MasterPendingTerminalNavigation {
    /**
     * Creates a new MasterPendingTerminalNavigation instance.
     * @param {Partial<MasterPendingTerminalNavigation>} [$$source = {}] - The source object to create the MasterPendingTerminalNavigation.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("broadcastId" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["broadcastId"] = "";
        }
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {TerminalNavigationDirection}
             */
            this["direction"] = TerminalNavigationDirection.$zero;
        }
        if (!("sourceTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalId"] = "";
        }
        if (!("sourceTerminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalName"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }
        if (!("commandName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandName"] = "";
        }
        if (!("targetTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetTerminalId"] = "";
        }
        if (!("targetTerminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetTerminalName"] = "";
        }
        if (!("routeDepth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["routeDepth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterPendingTerminalNavigation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterPendingTerminalNavigation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterPendingTerminalNavigation(/** @type {Partial<MasterPendingTerminalNavigation>} */($$parsedSource));
    }
}

/**
 * MasterRosterEntry is the Overseer view of one roster claim.
 */
export class MasterRosterEntry {
    /**
     * Creates a new MasterRosterEntry instance.
     * @param {Partial<MasterRosterEntry>} [$$source = {}] - The source object to create the MasterRosterEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {CharacterID}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("intelligence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["intelligence"] = 0;
        }
        if (!("hackerPerkAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hackerPerkAvailable"] = false;
        }
        if (!("claimedBySessionId" in $$source)) {
            /**
             * @member
             * @type {LogicalSessionID | null}
             */
            this["claimedBySessionId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterRosterEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterRosterEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterRosterEntry(/** @type {Partial<MasterRosterEntry>} */($$parsedSource));
    }
}

/**
 * MasterSessionEntry is the Overseer view of one recognized logical session.
 */
export class MasterSessionEntry {
    /**
     * Creates a new MasterSessionEntry instance.
     * @param {Partial<MasterSessionEntry>} [$$source = {}] - The source object to create the MasterSessionEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {LogicalSessionID}
             */
            this["id"] = "";
        }
        if (!("fallbackName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fallbackName"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("character" in $$source)) {
            /**
             * @member
             * @type {PlayerCharacter | null}
             */
            this["character"] = null;
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {PlayerRole}
             */
            this["role"] = PlayerRole.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterSessionEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterSessionEntry}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("character" in $$parsedSource) {
            $$parsedSource["character"] = $$createField3_0($$parsedSource["character"]);
        }
        return new MasterSessionEntry(/** @type {Partial<MasterSessionEntry>} */($$parsedSource));
    }
}

export class MasterTerminalNavigationNotice {
    /**
     * Creates a new MasterTerminalNavigationNotice instance.
     * @param {Partial<MasterTerminalNavigationNotice>} [$$source = {}] - The source object to create the MasterTerminalNavigationNotice.
     */
    constructor($$source = {}) {
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {TerminalNavigationNoticeReason}
             */
            this["reason"] = TerminalNavigationNoticeReason.$zero;
        }
        if (!("sourceTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalId"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["targetTerminalId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterTerminalNavigationNotice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterTerminalNavigationNotice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterTerminalNavigationNotice(/** @type {Partial<MasterTerminalNavigationNotice>} */($$parsedSource));
    }
}

/**
 * NavState is the shared server-authoritative player position.
 */
export class NavState {
    /**
     * Creates a new NavState instance.
     * @param {Partial<NavState>} [$$source = {}] - The source object to create the NavState.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["path"] = [];
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("viewEntryId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["viewEntryId"] = null;
        }
        if (!("commandNodeId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["commandNodeId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NavState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NavState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("path" in $$parsedSource) {
            $$parsedSource["path"] = $$createField0_0($$parsedSource["path"]);
        }
        return new NavState(/** @type {Partial<NavState>} */($$parsedSource));
    }
}

/**
 * PendingFacilityAction is the detached world-action intent captured during
 * the existing private command approval lifecycle.
 * @typedef {any} PendingFacilityAction
 */

export class PendingTerminalNavigationPresentation {
    /**
     * Creates a new PendingTerminalNavigationPresentation instance.
     * @param {Partial<PendingTerminalNavigationPresentation>} [$$source = {}] - The source object to create the PendingTerminalNavigationPresentation.
     */
    constructor($$source = {}) {
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {TerminalNavigationDirection}
             */
            this["direction"] = TerminalNavigationDirection.$zero;
        }
        if (!("targetTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetTerminalId"] = "";
        }
        if (!("targetTerminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetTerminalName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PendingTerminalNavigationPresentation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PendingTerminalNavigationPresentation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PendingTerminalNavigationPresentation(/** @type {Partial<PendingTerminalNavigationPresentation>} */($$parsedSource));
    }
}

/**
 * PlayerCharacter is the assigned identity visible at a projection boundary.
 */
export class PlayerCharacter {
    /**
     * Creates a new PlayerCharacter instance.
     * @param {Partial<PlayerCharacter>} [$$source = {}] - The source object to create the PlayerCharacter.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {CharacterID}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerCharacter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerCharacter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerCharacter(/** @type {Partial<PlayerCharacter>} */($$parsedSource));
    }
}

/**
 * PlayerConfigMetadata is the detached Overseer view of the active config.
 */
export class PlayerConfigMetadata {
    /**
     * Creates a new PlayerConfigMetadata instance.
     * @param {Partial<PlayerConfigMetadata>} [$$source = {}] - The source object to create the PlayerConfigMetadata.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerConfigMetadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerConfigMetadata}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerConfigMetadata(/** @type {Partial<PlayerConfigMetadata>} */($$parsedSource));
    }
}

/**
 * PlayerRole is a logical session's current broadcast-wide authority.
 * @readonly
 * @enum {string}
 */
export const PlayerRole = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerRoleUnassigned: "unassigned",
    PlayerRoleActive: "active",
    PlayerRoleObserver: "observer",
};

/**
 * PublicHackPattern is the client-safe projection of one current bracket span.
 */
export class PublicHackPattern {
    /**
     * Creates a new PublicHackPattern instance.
     * @param {Partial<PublicHackPattern>} [$$source = {}] - The source object to create the PublicHackPattern.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("row" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["row"] = 0;
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["used"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicHackPattern instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicHackPattern}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicHackPattern(/** @type {Partial<PublicHackPattern>} */($$parsedSource));
    }
}

/**
 * PublicHackState is the only hacking representation permitted at a client boundary.
 */
export class PublicHackState {
    /**
     * Creates a new PublicHackState instance.
     * @param {Partial<PublicHackState>} [$$source = {}] - The source object to create the PublicHackState.
     */
    constructor($$source = {}) {
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["level"] = 0;
        }
        if (!("wordLength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["wordLength"] = 0;
        }
        if (!("attemptsMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attemptsMax"] = 0;
        }
        if (!("attemptsLeft" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attemptsLeft"] = 0;
        }
        if (!("solved" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["solved"] = false;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["failed"] = false;
        }
        if (!("log" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["log"] = [];
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {HackColumn[]}
             */
            this["columns"] = [];
        }
        if (!("patterns" in $$source)) {
            /**
             * @member
             * @type {PublicHackPattern[]}
             */
            this["patterns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicHackState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicHackState}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType27;
        const $$createField8_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField6_0($$parsedSource["log"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField7_0($$parsedSource["columns"]);
        }
        if ("patterns" in $$parsedSource) {
            $$parsedSource["patterns"] = $$createField8_0($$parsedSource["patterns"]);
        }
        return new PublicHackState(/** @type {Partial<PublicHackState>} */($$parsedSource));
    }
}

/**
 * PublicLiveState is the immutable client-facing live snapshot.
 */
export class PublicLiveState {
    /**
     * Creates a new PublicLiveState instance.
     * @param {Partial<PublicLiveState>} [$$source = {}] - The source object to create the PublicLiveState.
     */
    constructor($$source = {}) {
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }
        if (!("terminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalName"] = "";
        }
        if (!("tree" in $$source)) {
            /**
             * @member
             * @type {ContentNode}
             */
            this["tree"] = null;
        }
        if (!("hackLevel" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hackLevel"] = 0;
        }
        if (!("introText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["introText"] = "";
        }
        if (!("nav" in $$source)) {
            /**
             * @member
             * @type {NavState}
             */
            this["nav"] = (new NavState());
        }
        if (!("hack" in $$source)) {
            /**
             * @member
             * @type {PublicHackState | null}
             */
            this["hack"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CommandExecutionPresentation | null | undefined}
             */
            this["commandExecution"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TerminalNavigationPresentation | null | undefined}
             */
            this["terminalNavigation"] = undefined;
        }
        if (!("controllerPresentation" in $$source)) {
            /**
             * @member
             * @type {ControllerTerminalPresentation}
             */
            this["controllerPresentation"] = (new ControllerTerminalPresentation());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TerminalPresentationEffect[] | undefined}
             */
            this["effects"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicLiveState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicLiveState}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType30;
        const $$createField6_0 = $$createType32;
        const $$createField7_0 = $$createType34;
        const $$createField8_0 = $$createType36;
        const $$createField9_0 = $$createType37;
        const $$createField10_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nav" in $$parsedSource) {
            $$parsedSource["nav"] = $$createField5_0($$parsedSource["nav"]);
        }
        if ("hack" in $$parsedSource) {
            $$parsedSource["hack"] = $$createField6_0($$parsedSource["hack"]);
        }
        if ("commandExecution" in $$parsedSource) {
            $$parsedSource["commandExecution"] = $$createField7_0($$parsedSource["commandExecution"]);
        }
        if ("terminalNavigation" in $$parsedSource) {
            $$parsedSource["terminalNavigation"] = $$createField8_0($$parsedSource["terminalNavigation"]);
        }
        if ("controllerPresentation" in $$parsedSource) {
            $$parsedSource["controllerPresentation"] = $$createField9_0($$parsedSource["controllerPresentation"]);
        }
        if ("effects" in $$parsedSource) {
            $$parsedSource["effects"] = $$createField10_0($$parsedSource["effects"]);
        }
        return new PublicLiveState(/** @type {Partial<PublicLiveState>} */($$parsedSource));
    }
}

/**
 * ServerInfo is safe status displayed to the Overseer.
 */
export class ServerInfo {
    /**
     * Creates a new ServerInfo instance.
     * @param {Partial<ServerInfo>} [$$source = {}] - The source object to create the ServerInfo.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["localUrl"] = undefined;
        }
        if (!("tunnel" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tunnel"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tunnelError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfo(/** @type {Partial<ServerInfo>} */($$parsedSource));
    }
}

/**
 * Session is the durable version-1 campaign document.
 * @typedef {any} Session
 */

/**
 * SwitchID identifies one pending terminal-switch decision.
 * @typedef {string} SwitchID
 */

/**
 * TerminalGroup is the durable high-level representation of one ordered set
 * of terminals. A standalone terminal is represented by a one-member group.
 */
export class TerminalGroup {
    /**
     * Creates a new TerminalGroup instance.
     * @param {Partial<TerminalGroup>} [$$source = {}] - The source object to create the TerminalGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("terminalIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["terminalIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terminalIds" in $$parsedSource) {
            $$parsedSource["terminalIds"] = $$createField2_0($$parsedSource["terminalIds"]);
        }
        return new TerminalGroup(/** @type {Partial<TerminalGroup>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TerminalNavigationDecision = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalNavigationApprove: "approve",
    TerminalNavigationReject: "reject",
};

/**
 * TerminalNavigationDirection distinguishes forward links from LIFO returns.
 * @readonly
 * @enum {string}
 */
export const TerminalNavigationDirection = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalNavigationForward: "forward",
    TerminalNavigationReturn: "return",
};

/**
 * TerminalNavigationNoticeReason is a safe private failure category.
 * @readonly
 * @enum {string}
 */
export const TerminalNavigationNoticeReason = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalNavigationNoticeTargetMissing: "target-missing",
    TerminalNavigationNoticeSelfTarget: "self-target",
    TerminalNavigationNoticeCommandStale: "command-stale",
    TerminalNavigationNoticeTargetChanged: "target-changed",
};

export class TerminalNavigationPresentation {
    /**
     * Creates a new TerminalNavigationPresentation instance.
     * @param {Partial<TerminalNavigationPresentation>} [$$source = {}] - The source object to create the TerminalNavigationPresentation.
     */
    constructor($$source = {}) {
        if (!("routeDepth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["routeDepth"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TerminalReturnTarget | null | undefined}
             */
            this["returnTarget"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PendingTerminalNavigationPresentation | null | undefined}
             */
            this["pending"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalNavigationPresentation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalNavigationPresentation}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType40;
        const $$createField2_0 = $$createType42;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("returnTarget" in $$parsedSource) {
            $$parsedSource["returnTarget"] = $$createField1_0($$parsedSource["returnTarget"]);
        }
        if ("pending" in $$parsedSource) {
            $$parsedSource["pending"] = $$createField2_0($$parsedSource["pending"]);
        }
        return new TerminalNavigationPresentation(/** @type {Partial<TerminalNavigationPresentation>} */($$parsedSource));
    }
}

/**
 * TerminalPresentationEffect is a safe, presentation-only terminal effect.
 * @readonly
 * @enum {string}
 */
export const TerminalPresentationEffect = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalPresentationEffectUnspecified: "",
    TerminalPresentationEffectDisplayUnstable: "display-unstable",
};

export class TerminalReturnTarget {
    /**
     * Creates a new TerminalReturnTarget instance.
     * @param {Partial<TerminalReturnTarget>} [$$source = {}] - The source object to create the TerminalReturnTarget.
     */
    constructor($$source = {}) {
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }
        if (!("terminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalReturnTarget instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalReturnTarget}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalReturnTarget(/** @type {Partial<TerminalReturnTarget>} */($$parsedSource));
    }
}

/**
 * TerminalSwitchChoice is the Overseer's explicit unfinished-puzzle decision.
 * @readonly
 * @enum {string}
 */
export const TerminalSwitchChoice = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalSwitchPreserve: "preserve",
    TerminalSwitchDiscard: "discard",
    TerminalSwitchCancel: "cancel",
};

// Private type creation functions
const $$createType0 = FacilityEntityReference.createFrom;
const $$createType1 = FacilityDependency.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FacilityIssue.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = HackWord.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = PlayerConfigMetadata.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = MasterRosterEntry.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = MasterSessionEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = MasterBroadcastState.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = MasterPendingSwitch.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = MasterPendingCommandExecution.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = MasterPendingTerminalNavigation.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = MasterTerminalNavigationNotice.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = PlayerCharacter.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = HackColumn.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = PublicHackPattern.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = NavState.createFrom;
const $$createType31 = PublicHackState.createFrom;
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = CommandExecutionPresentation.createFrom;
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = TerminalNavigationPresentation.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = ControllerTerminalPresentation.createFrom;
const $$createType38 = $Create.Array($Create.Any);
const $$createType39 = TerminalReturnTarget.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = PendingTerminalNavigationPresentation.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
