// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";

/**
 * ApplicationUpdateCommandResult includes the authoritative snapshot for
 * both accepted and rejected decisions.
 */
export class ApplicationUpdateCommandResult {
    /**
     * Creates a new ApplicationUpdateCommandResult instance.
     * @param {Partial<ApplicationUpdateCommandResult>} [$$source = {}] - The source object to create the ApplicationUpdateCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("snapshot" in $$source)) {
            /**
             * @member
             * @type {ApplicationUpdateSnapshot}
             */
            this["snapshot"] = (new ApplicationUpdateSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationUpdateCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplicationUpdateCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField2_0($$parsedSource["snapshot"]);
        }
        return new ApplicationUpdateCommandResult(/** @type {Partial<ApplicationUpdateCommandResult>} */($$parsedSource));
    }
}

export class ApplicationUpdateOfferDecisionPayload {
    /**
     * Creates a new ApplicationUpdateOfferDecisionPayload instance.
     * @param {Partial<ApplicationUpdateOfferDecisionPayload>} [$$source = {}] - The source object to create the ApplicationUpdateOfferDecisionPayload.
     */
    constructor($$source = {}) {
        if (!("attemptId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["attemptId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationUpdateOfferDecisionPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplicationUpdateOfferDecisionPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationUpdateOfferDecisionPayload(/** @type {Partial<ApplicationUpdateOfferDecisionPayload>} */($$parsedSource));
    }
}

export class ApplicationUpdateRestartDecisionPayload {
    /**
     * Creates a new ApplicationUpdateRestartDecisionPayload instance.
     * @param {Partial<ApplicationUpdateRestartDecisionPayload>} [$$source = {}] - The source object to create the ApplicationUpdateRestartDecisionPayload.
     */
    constructor($$source = {}) {
        if (!("attemptId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["attemptId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["decision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationUpdateRestartDecisionPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplicationUpdateRestartDecisionPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationUpdateRestartDecisionPayload(/** @type {Partial<ApplicationUpdateRestartDecisionPayload>} */($$parsedSource));
    }
}

/**
 * ApplicationUpdateSnapshot is the narrow, non-sensitive update projection
 * exposed to the Overseer. Provider metadata, verification evidence, local
 * paths, and helper state remain behind the native boundary.
 */
export class ApplicationUpdateSnapshot {
    /**
     * Creates a new ApplicationUpdateSnapshot instance.
     * @param {Partial<ApplicationUpdateSnapshot>} [$$source = {}] - The source object to create the ApplicationUpdateSnapshot.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["attemptId"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("installedVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installedVersion"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["availableVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["releaseNotes"] = undefined;
        }
        if (!("bytesDownloaded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bytesDownloaded"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["downloadSize"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["failedStage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["recoveryAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplicationUpdateSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApplicationUpdateSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplicationUpdateSnapshot(/** @type {Partial<ApplicationUpdateSnapshot>} */($$parsedSource));
    }
}

/**
 * AssignmentPayload assigns one available character to one unassigned
 * logical session.
 */
export class AssignmentPayload {
    /**
     * Creates a new AssignmentPayload instance.
     * @param {Partial<AssignmentPayload>} [$$source = {}] - The source object to create the AssignmentPayload.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {domain$0.LogicalSessionID}
             */
            this["sessionId"] = "";
        }
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {domain$0.CharacterID}
             */
            this["characterId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssignmentPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssignmentPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssignmentPayload(/** @type {Partial<AssignmentPayload>} */($$parsedSource));
    }
}

/**
 * CharacterCreatePayload carries one complete trusted player profile and the
 * coordination revision it was based on.
 */
export class CharacterCreatePayload {
    /**
     * Creates a new CharacterCreatePayload instance.
     * @param {Partial<CharacterCreatePayload>} [$$source = {}] - The source object to create the CharacterCreatePayload.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("intelligence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["intelligence"] = 0;
        }
        if (!("hackerPerkAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["hackerPerkAvailable"] = null;
        }
        if (!("expectedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedRevision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterCreatePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CharacterCreatePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CharacterCreatePayload(/** @type {Partial<CharacterCreatePayload>} */($$parsedSource));
    }
}

/**
 * CharacterDeletePayload identifies one stable roster identity and the
 * coordination revision the deletion was based on.
 */
export class CharacterDeletePayload {
    /**
     * Creates a new CharacterDeletePayload instance.
     * @param {Partial<CharacterDeletePayload>} [$$source = {}] - The source object to create the CharacterDeletePayload.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {domain$0.CharacterID}
             */
            this["characterId"] = "";
        }
        if (!("expectedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedRevision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterDeletePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CharacterDeletePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CharacterDeletePayload(/** @type {Partial<CharacterDeletePayload>} */($$parsedSource));
    }
}

/**
 * CharacterUpdatePayload carries a complete replacement profile for one
 * stable roster identity and the coordination revision it was based on.
 */
export class CharacterUpdatePayload {
    /**
     * Creates a new CharacterUpdatePayload instance.
     * @param {Partial<CharacterUpdatePayload>} [$$source = {}] - The source object to create the CharacterUpdatePayload.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {domain$0.CharacterID}
             */
            this["characterId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("intelligence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["intelligence"] = 0;
        }
        if (!("hackerPerkAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean | null}
             */
            this["hackerPerkAvailable"] = null;
        }
        if (!("expectedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedRevision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterUpdatePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CharacterUpdatePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CharacterUpdatePayload(/** @type {Partial<CharacterUpdatePayload>} */($$parsedSource));
    }
}

/**
 * CommandExecutionDecisionPayload resolves one exact server-owned pending
 * request. The authored prompt itself is carried only by coordination state.
 */
export class CommandExecutionDecisionPayload {
    /**
     * Creates a new CommandExecutionDecisionPayload instance.
     * @param {Partial<CommandExecutionDecisionPayload>} [$$source = {}] - The source object to create the CommandExecutionDecisionPayload.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {domain$0.CommandExecutionDecision}
             */
            this["decision"] = domain$0.CommandExecutionDecision.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandExecutionDecisionPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandExecutionDecisionPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandExecutionDecisionPayload(/** @type {Partial<CommandExecutionDecisionPayload>} */($$parsedSource));
    }
}

/**
 * CommandResult is used for privileged commands that do not return a model.
 */
export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

/**
 * CoordinationCommandResult returns the authoritative detached state for
 * both accepted and rejected roster/broadcast commands.
 */
export class CoordinationCommandResult {
    /**
     * Creates a new CoordinationCommandResult instance.
     * @param {Partial<CoordinationCommandResult>} [$$source = {}] - The source object to create the CoordinationCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoordinationCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CoordinationCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        return new CoordinationCommandResult(/** @type {Partial<CoordinationCommandResult>} */($$parsedSource));
    }
}

/**
 * GeneratedPlayerPasswordResult is deliberately not reusable and contains no
 * snapshot. GeneratedPassword is populated only after secure-store replacement
 * and settings persistence both succeed.
 */
export class GeneratedPlayerPasswordResult {
    /**
     * Creates a new GeneratedPlayerPasswordResult instance.
     * @param {Partial<GeneratedPlayerPasswordResult>} [$$source = {}] - The source object to create the GeneratedPlayerPasswordResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["generatedPassword"] = undefined;
        }
        if (!("settingsRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["settingsRevision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeneratedPlayerPasswordResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GeneratedPlayerPasswordResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GeneratedPlayerPasswordResult(/** @type {Partial<GeneratedPlayerPasswordResult>} */($$parsedSource));
    }
}

/**
 * LiveTerminalPayload is the validated set-live bridge input.
 */
export class LiveTerminalPayload {
    /**
     * Creates a new LiveTerminalPayload instance.
     * @param {Partial<LiveTerminalPayload>} [$$source = {}] - The source object to create the LiveTerminalPayload.
     */
    constructor($$source = {}) {
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }
        if (!("terminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalName"] = "";
        }
        if (!("tree" in $$source)) {
            /**
             * @member
             * @type {domain$0.ContentNode}
             */
            this["tree"] = null;
        }
        if (!("hackLevel" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hackLevel"] = 0;
        }
        if (!("introText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["introText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveTerminalPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LiveTerminalPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveTerminalPayload(/** @type {Partial<LiveTerminalPayload>} */($$parsedSource));
    }
}

/**
 * LiveUpdatePayload replaces published content without resetting a puzzle.
 */
export class LiveUpdatePayload {
    /**
     * Creates a new LiveUpdatePayload instance.
     * @param {Partial<LiveUpdatePayload>} [$$source = {}] - The source object to create the LiveUpdatePayload.
     */
    constructor($$source = {}) {
        if (!("tree" in $$source)) {
            /**
             * @member
             * @type {domain$0.ContentNode}
             */
            this["tree"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["introText"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveUpdatePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LiveUpdatePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveUpdatePayload(/** @type {Partial<LiveUpdatePayload>} */($$parsedSource));
    }
}

/**
 * LogicalSessionRenamePayload changes only a process-local fallback label.
 */
export class LogicalSessionRenamePayload {
    /**
     * Creates a new LogicalSessionRenamePayload instance.
     * @param {Partial<LogicalSessionRenamePayload>} [$$source = {}] - The source object to create the LogicalSessionRenamePayload.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {domain$0.LogicalSessionID}
             */
            this["sessionId"] = "";
        }
        if (!("fallbackName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fallbackName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogicalSessionRenamePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogicalSessionRenamePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogicalSessionRenamePayload(/** @type {Partial<LogicalSessionRenamePayload>} */($$parsedSource));
    }
}

/**
 * MoveCharacterPayload atomically transfers one stable character identity.
 */
export class MoveCharacterPayload {
    /**
     * Creates a new MoveCharacterPayload instance.
     * @param {Partial<MoveCharacterPayload>} [$$source = {}] - The source object to create the MoveCharacterPayload.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {domain$0.CharacterID}
             */
            this["characterId"] = "";
        }
        if (!("toSessionId" in $$source)) {
            /**
             * @member
             * @type {domain$0.LogicalSessionID}
             */
            this["toSessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveCharacterPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveCharacterPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveCharacterPayload(/** @type {Partial<MoveCharacterPayload>} */($$parsedSource));
    }
}

/**
 * PlayerConfigCommandResult combines durable metadata with authoritative roster state.
 */
export class PlayerConfigCommandResult {
    /**
     * Creates a new PlayerConfigCommandResult instance.
     * @param {Partial<PlayerConfigCommandResult>} [$$source = {}] - The source object to create the PlayerConfigCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("canceled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canceled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.PlayerConfigMetadata | null | undefined}
             */
            this["playerConfig"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.Session | null | undefined}
             */
            this["session"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerConfigCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerConfigCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType4;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("playerConfig" in $$parsedSource) {
            $$parsedSource["playerConfig"] = $$createField3_0($$parsedSource["playerConfig"]);
        }
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField5_0($$parsedSource["state"]);
        }
        return new PlayerConfigCommandResult(/** @type {Partial<PlayerConfigCommandResult>} */($$parsedSource));
    }
}

export class PublicAccessCommandPayload {
    /**
     * Creates a new PublicAccessCommandPayload instance.
     * @param {Partial<PublicAccessCommandPayload>} [$$source = {}] - The source object to create the PublicAccessCommandPayload.
     */
    constructor($$source = {}) {
        if (!("expectedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedRevision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicAccessCommandPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicAccessCommandPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicAccessCommandPayload(/** @type {Partial<PublicAccessCommandPayload>} */($$parsedSource));
    }
}

export class PublicAccessCommandResult {
    /**
     * Creates a new PublicAccessCommandResult instance.
     * @param {Partial<PublicAccessCommandResult>} [$$source = {}] - The source object to create the PublicAccessCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("snapshot" in $$source)) {
            /**
             * @member
             * @type {PublicAccessSnapshot}
             */
            this["snapshot"] = (new PublicAccessSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicAccessCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicAccessCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField2_0($$parsedSource["snapshot"]);
        }
        return new PublicAccessCommandResult(/** @type {Partial<PublicAccessCommandResult>} */($$parsedSource));
    }
}

/**
 * PublicAccessPreferences is the secret-free native desktop projection.
 */
export class PublicAccessPreferences {
    /**
     * Creates a new PublicAccessPreferences instance.
     * @param {Partial<PublicAccessPreferences>} [$$source = {}] - The source object to create the PublicAccessPreferences.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("enabledPreference" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabledPreference"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reservedDomain"] = undefined;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("providerTokenPresentHint" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["providerTokenPresentHint"] = false;
        }
        if (!("playerPasswordPresentHint" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["playerPasswordPresentHint"] = false;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicAccessPreferences instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicAccessPreferences}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicAccessPreferences(/** @type {Partial<PublicAccessPreferences>} */($$parsedSource));
    }
}

export class PublicAccessSnapshot {
    /**
     * Creates a new PublicAccessSnapshot instance.
     * @param {Partial<PublicAccessSnapshot>} [$$source = {}] - The source object to create the PublicAccessSnapshot.
     */
    constructor($$source = {}) {
        if (!("preferences" in $$source)) {
            /**
             * @member
             * @type {PublicAccessPreferences}
             */
            this["preferences"] = (new PublicAccessPreferences());
        }
        if (!("providerTokenPresence" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["providerTokenPresence"] = "";
        }
        if (!("playerPasswordPresence" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["playerPasswordPresence"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {PublicAccessStatus}
             */
            this["status"] = (new PublicAccessStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicAccessSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicAccessSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preferences" in $$parsedSource) {
            $$parsedSource["preferences"] = $$createField0_0($$parsedSource["preferences"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        return new PublicAccessSnapshot(/** @type {Partial<PublicAccessSnapshot>} */($$parsedSource));
    }
}

export class PublicAccessStatus {
    /**
     * Creates a new PublicAccessStatus instance.
     * @param {Partial<PublicAccessStatus>} [$$source = {}] - The source object to create the PublicAccessStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (!("settingsRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["settingsRevision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["publicUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorCategory"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["errorMessage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicAccessStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicAccessStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicAccessStatus(/** @type {Partial<PublicAccessStatus>} */($$parsedSource));
    }
}

/**
 * ResetCommandStatePayload addresses one authored state-changing command by
 * stable terminal and command IDs.
 */
export class ResetCommandStatePayload {
    /**
     * Creates a new ResetCommandStatePayload instance.
     * @param {Partial<ResetCommandStatePayload>} [$$source = {}] - The source object to create the ResetCommandStatePayload.
     */
    constructor($$source = {}) {
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetCommandStatePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResetCommandStatePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetCommandStatePayload(/** @type {Partial<ResetCommandStatePayload>} */($$parsedSource));
    }
}

/**
 * ResetTerminalCommandStatesPayload addresses one authored terminal whose
 * durable command snapshots should be cleared atomically.
 */
export class ResetTerminalCommandStatesPayload {
    /**
     * Creates a new ResetTerminalCommandStatesPayload instance.
     * @param {Partial<ResetTerminalCommandStatesPayload>} [$$source = {}] - The source object to create the ResetTerminalCommandStatesPayload.
     */
    constructor($$source = {}) {
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetTerminalCommandStatesPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResetTerminalCommandStatesPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetTerminalCommandStatesPayload(/** @type {Partial<ResetTerminalCommandStatesPayload>} */($$parsedSource));
    }
}

/**
 * ResolveCommandExecutionResult is the private Overseer-only response to one
 * exact pending command decision.
 */
export class ResolveCommandExecutionResult {
    /**
     * Creates a new ResolveCommandExecutionResult instance.
     * @param {Partial<ResolveCommandExecutionResult>} [$$source = {}] - The source object to create the ResolveCommandExecutionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveCommandExecutionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolveCommandExecutionResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        return new ResolveCommandExecutionResult(/** @type {Partial<ResolveCommandExecutionResult>} */($$parsedSource));
    }
}

/**
 * ResolveTerminalNavigationResult is the private response for one exact
 * forward/return decision and its resulting authoritative coordination state.
 */
export class ResolveTerminalNavigationResult {
    /**
     * Creates a new ResolveTerminalNavigationResult instance.
     * @param {Partial<ResolveTerminalNavigationResult>} [$$source = {}] - The source object to create the ResolveTerminalNavigationResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveTerminalNavigationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolveTerminalNavigationResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        return new ResolveTerminalNavigationResult(/** @type {Partial<ResolveTerminalNavigationResult>} */($$parsedSource));
    }
}

/**
 * RuntimeStatus is the synchronous startup/status snapshot used to avoid
 * losing events emitted before the frontend subscribes.
 */
export class RuntimeStatus {
    /**
     * Creates a new RuntimeStatus instance.
     * @param {Partial<RuntimeStatus>} [$$source = {}] - The source object to create the RuntimeStatus.
     */
    constructor($$source = {}) {
        if (!("serverInfo" in $$source)) {
            /**
             * @member
             * @type {domain$0.ServerInfo | null}
             */
            this["serverInfo"] = null;
        }
        if (!("clientCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clientCount"] = 0;
        }
        if (!("hackState" in $$source)) {
            /**
             * @member
             * @type {domain$0.PublicHackState | null}
             */
            this["hackState"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startupError"] = undefined;
        }
        if (!("saveState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveState"] = "";
        }
        if (!("requestedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestedRevision"] = 0;
        }
        if (!("savedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["savedRevision"] = 0;
        }
        if (!("coordinationState" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["coordinationState"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeStatus}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField2_0 = $$createType11;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serverInfo" in $$parsedSource) {
            $$parsedSource["serverInfo"] = $$createField0_0($$parsedSource["serverInfo"]);
        }
        if ("hackState" in $$parsedSource) {
            $$parsedSource["hackState"] = $$createField2_0($$parsedSource["hackState"]);
        }
        if ("coordinationState" in $$parsedSource) {
            $$parsedSource["coordinationState"] = $$createField7_0($$parsedSource["coordinationState"]);
        }
        return new RuntimeStatus(/** @type {Partial<RuntimeStatus>} */($$parsedSource));
    }
}

/**
 * SavePublicAccessSettingsPayload is ephemeral trusted input. Its secret
 * fields are consumed into byte buffers and are never copied into a result,
 * event, status, or persistence model.
 */
export class SavePublicAccessSettingsPayload {
    /**
     * Creates a new SavePublicAccessSettingsPayload instance.
     * @param {Partial<SavePublicAccessSettingsPayload>} [$$source = {}] - The source object to create the SavePublicAccessSettingsPayload.
     */
    constructor($$source = {}) {
        if (!("expectedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedRevision"] = 0;
        }
        if (!("enabledPreference" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabledPreference"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["reservedDomain"] = undefined;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["replacementProviderToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["deleteProviderToken"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["replacementPlayerPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["deletePlayerPassword"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavePublicAccessSettingsPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavePublicAccessSettingsPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavePublicAccessSettingsPayload(/** @type {Partial<SavePublicAccessSettingsPayload>} */($$parsedSource));
    }
}

/**
 * SessionStateEvent is emitted only after a command-state mutation reaches
 * durability. It intentionally excludes the user-selected file path.
 */
export class SessionStateEvent {
    /**
     * Creates a new SessionStateEvent instance.
     * @param {Partial<SessionStateEvent>} [$$source = {}] - The source object to create the SessionStateEvent.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("session" in $$source)) {
            /**
             * @member
             * @type {domain$0.Session | null}
             */
            this["session"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStateEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionStateEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionStateEvent(/** @type {Partial<SessionStateEvent>} */($$parsedSource));
    }
}

/**
 * SessionStateResult returns the canonical durable document and its
 * session-owned revision after a trusted command-state mutation.
 */
export class SessionStateResult {
    /**
     * Creates a new SessionStateResult instance.
     * @param {Partial<SessionStateResult>} [$$source = {}] - The source object to create the SessionStateResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.Session | null | undefined}
             */
            this["session"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionStateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionStateResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionStateResult(/** @type {Partial<SessionStateResult>} */($$parsedSource));
    }
}

/**
 * TerminalGroupReplacementPayload is the private complete-set authoring
 * request. Both revisions are captured from the canonical state reviewed by
 * the Overseer.
 */
export class TerminalGroupReplacementPayload {
    /**
     * Creates a new TerminalGroupReplacementPayload instance.
     * @param {Partial<TerminalGroupReplacementPayload>} [$$source = {}] - The source object to create the TerminalGroupReplacementPayload.
     */
    constructor($$source = {}) {
        if (!("terminalGroups" in $$source)) {
            /**
             * @member
             * @type {domain$0.TerminalGroup[]}
             */
            this["terminalGroups"] = [];
        }
        if (!("expectedSessionRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedSessionRevision"] = 0;
        }
        if (!("expectedCoordinationRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["expectedCoordinationRevision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGroupReplacementPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalGroupReplacementPayload}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terminalGroups" in $$parsedSource) {
            $$parsedSource["terminalGroups"] = $$createField0_0($$parsedSource["terminalGroups"]);
        }
        return new TerminalGroupReplacementPayload(/** @type {Partial<TerminalGroupReplacementPayload>} */($$parsedSource));
    }
}

/**
 * TerminalGroupReplacementResult returns both authoritative owners on success
 * and on stale rejection so the frontend never keeps an optimistic draft.
 */
export class TerminalGroupReplacementResult {
    /**
     * Creates a new TerminalGroupReplacementResult instance.
     * @param {Partial<TerminalGroupReplacementResult>} [$$source = {}] - The source object to create the TerminalGroupReplacementResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("sessionRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sessionRevision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.Session | null | undefined}
             */
            this["session"] = undefined;
        }
        if (!("coordinationState" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["coordinationState"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGroupReplacementResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalGroupReplacementResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("coordinationState" in $$parsedSource) {
            $$parsedSource["coordinationState"] = $$createField4_0($$parsedSource["coordinationState"]);
        }
        return new TerminalGroupReplacementResult(/** @type {Partial<TerminalGroupReplacementResult>} */($$parsedSource));
    }
}

export class TerminalNavigationDecisionPayload {
    /**
     * Creates a new TerminalNavigationDecisionPayload instance.
     * @param {Partial<TerminalNavigationDecisionPayload>} [$$source = {}] - The source object to create the TerminalNavigationDecisionPayload.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {domain$0.TerminalNavigationDecision}
             */
            this["decision"] = domain$0.TerminalNavigationDecision.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalNavigationDecisionPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalNavigationDecisionPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalNavigationDecisionPayload(/** @type {Partial<TerminalNavigationDecisionPayload>} */($$parsedSource));
    }
}

/**
 * TerminalSwitchCommandResult describes either a completed terminal selection
 * or a later decision gate. SwitchID remains empty for direct activation and
 * clear operations; unfinished-puzzle choices populate it in the US8 flow.
 */
export class TerminalSwitchCommandResult {
    /**
     * Creates a new TerminalSwitchCommandResult instance.
     * @param {Partial<TerminalSwitchCommandResult>} [$$source = {}] - The source object to create the TerminalSwitchCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.SwitchID | undefined}
             */
            this["switchId"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSwitchCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalSwitchCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField4_0($$parsedSource["state"]);
        }
        return new TerminalSwitchCommandResult(/** @type {Partial<TerminalSwitchCommandResult>} */($$parsedSource));
    }
}

/**
 * TerminalSwitchDecisionPayload resolves one opaque unfinished-puzzle switch
 * request with an exact allowlisted decision.
 */
export class TerminalSwitchDecisionPayload {
    /**
     * Creates a new TerminalSwitchDecisionPayload instance.
     * @param {Partial<TerminalSwitchDecisionPayload>} [$$source = {}] - The source object to create the TerminalSwitchDecisionPayload.
     */
    constructor($$source = {}) {
        if (!("switchId" in $$source)) {
            /**
             * @member
             * @type {domain$0.SwitchID}
             */
            this["switchId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {domain$0.TerminalSwitchChoice}
             */
            this["decision"] = domain$0.TerminalSwitchChoice.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSwitchDecisionPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalSwitchDecisionPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalSwitchDecisionPayload(/** @type {Partial<TerminalSwitchDecisionPayload>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ApplicationUpdateSnapshot.createFrom;
const $$createType1 = domain$0.MasterCoordinationState.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = domain$0.PlayerConfigMetadata.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = PublicAccessSnapshot.createFrom;
const $$createType6 = PublicAccessPreferences.createFrom;
const $$createType7 = PublicAccessStatus.createFrom;
const $$createType8 = domain$0.ServerInfo.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = domain$0.PublicHackState.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = domain$0.TerminalGroup.createFrom;
const $$createType13 = $Create.Array($$createType12);
