// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../obalunenko/Fallout-Terminal/v2/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as domain$0 from "../../../../obalunenko/Fallout-Terminal/v2/internal/domain/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "client-count": number;
            "coordination-state": domain$0.MasterCoordinationState | null;
            "hack-state": domain$0.PublicHackState | null;
            "public-access-status": main$0.PublicAccessSnapshot;
            "server-info": domain$0.ServerInfo;
            "session-state": main$0.SessionStateEvent;
        }
    }
}
