//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../obalunenko/Fallout-Terminal/v2/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../../../obalunenko/Fallout-Terminal/v2/internal/domain/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "coordination-state": $$createType1,
        "hack-state": $$createType3,
        "public-access-status": $$createType4,
        "server-info": $$createType5,
        "session-state": $$createType6,
    }));
}

// Private type creation functions
const $$createType0 = domain$0.MasterCoordinationState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = domain$0.PublicHackState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = main$0.PublicAccessSnapshot.createFrom;
const $$createType5 = domain$0.ServerInfo.createFrom;
const $$createType6 = main$0.SessionStateEvent.createFrom;

configure();
