//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../obalunenko/Fallout-Terminal/v2/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../../../../obalunenko/Fallout-Terminal/v2/internal/domain/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "application-update-status": $$createType0,
        "coordination-state": $$createType2,
        "hack-state": $$createType4,
        "public-access-status": $$createType5,
        "server-info": $$createType6,
        "session-state": $$createType7,
    }));
}

// Private type creation functions
const $$createType0 = main$0.ApplicationUpdateSnapshot.createFrom;
const $$createType1 = domain$0.MasterCoordinationState.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = domain$0.PublicHackState.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = main$0.PublicAccessSnapshot.createFrom;
const $$createType6 = domain$0.ServerInfo.createFrom;
const $$createType7 = main$0.SessionStateEvent.createFrom;

configure();
