// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * desktopService is the complete generated desktop allowlist. It forwards to
 * the transport-neutral core so validation, protobuf adapters, authorization,
 * persistence, and redaction remain owned by existing application services.
 * The core App itself is deliberately never registered with Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./internal/session/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function AddCharacter(name) {
    return $Call.ByID(3737199611, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.AssignmentPayload} payload
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function AssignCharacter(payload) {
    return $Call.ByID(2389976051, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<session$0.SessionResult>}
 */
export function CopyDemo() {
    return $Call.ByID(2528704859).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} characterID
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function DeleteCharacter(characterID) {
    return $Call.ByID(1813121085, characterID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function EndBroadcast() {
    return $Call.ByID(3111437997).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function ForceHackSuccess() {
    return $Call.ByID(900713832).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.PublicAccessCommandPayload} payload
 * @returns {$CancellablePromise<$models.GeneratedPlayerPasswordResult>}
 */
export function GeneratePlayerPassword(payload) {
    return $Call.ByID(2485398858, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PublicAccessSnapshot>}
 */
export function GetPublicAccess() {
    return $Call.ByID(760826452).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.RuntimeStatus>}
 */
export function GetRuntimeStatus() {
    return $Call.ByID(858476939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PlayerConfigCommandResult>}
 */
export function LoadReferencedPlayerConfig() {
    return $Call.ByID(3625309117).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {$models.MoveCharacterPayload} payload
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function MoveCharacter(payload) {
    return $Call.ByID(604018779, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PlayerConfigCommandResult>}
 */
export function NewPlayerConfig() {
    return $Call.ByID(1361487498).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<session$0.SessionResult>}
 */
export function NewSession() {
    return $Call.ByID(3912692115).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PlayerConfigCommandResult>}
 */
export function OpenPlayerConfig() {
    return $Call.ByID(3818260626).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<session$0.SessionResult>}
 */
export function OpenSession() {
    return $Call.ByID(3087464523).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.CommandResult>}
 */
export function OpenURL(rawURL) {
    return $Call.ByID(1777024122, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function ReleaseCharacter(sessionID) {
    return $Call.ByID(4229942025, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.CharacterRenamePayload} payload
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function RenameCharacter(payload) {
    return $Call.ByID(547121714, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.LogicalSessionRenamePayload} payload
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function RenameLogicalSession(payload) {
    return $Call.ByID(1321706894, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.LiveTerminalPayload} payload
 * @returns {$CancellablePromise<$models.TerminalSwitchCommandResult>}
 */
export function RequestTerminalActivation(payload) {
    return $Call.ByID(2107315930, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TerminalSwitchCommandResult>}
 */
export function RequestTerminalClear() {
    return $Call.ByID(2661250323).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.LiveTerminalPayload} payload
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function ResetFailedHack(payload) {
    return $Call.ByID(3611622520, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.TerminalSwitchDecisionPayload} payload
 * @returns {$CancellablePromise<$models.TerminalSwitchCommandResult>}
 */
export function ResolveTerminalSwitch(payload) {
    return $Call.ByID(3005579231, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.SavePublicAccessSettingsPayload} payload
 * @returns {$CancellablePromise<$models.PublicAccessCommandResult>}
 */
export function SavePublicAccessSettings(payload) {
    return $Call.ByID(2107763802, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {domain$0.Session} session
 * @returns {$CancellablePromise<session$0.SaveResult>}
 */
export function SaveSession(session) {
    return $Call.ByID(830349524, session).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function SetActiveController(sessionID) {
    return $Call.ByID(3767238137, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function StartBroadcast() {
    return $Call.ByID(558580862).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.PublicAccessCommandPayload} payload
 * @returns {$CancellablePromise<$models.PublicAccessCommandResult>}
 */
export function StartPublicAccess(payload) {
    return $Call.ByID(2229627868, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {$models.PublicAccessCommandPayload} payload
 * @returns {$CancellablePromise<$models.PublicAccessCommandResult>}
 */
export function StopPublicAccess(payload) {
    return $Call.ByID(887374898, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {$models.LiveUpdatePayload} payload
 * @returns {$CancellablePromise<$models.CoordinationCommandResult>}
 */
export function UpdateLiveTerminal(payload) {
    return $Call.ByID(3618374702, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CoordinationCommandResult.createFrom;
const $$createType1 = session$0.SessionResult.createFrom;
const $$createType2 = $models.CommandResult.createFrom;
const $$createType3 = $models.GeneratedPlayerPasswordResult.createFrom;
const $$createType4 = $models.PublicAccessSnapshot.createFrom;
const $$createType5 = $models.RuntimeStatus.createFrom;
const $$createType6 = $models.PlayerConfigCommandResult.createFrom;
const $$createType7 = $models.TerminalSwitchCommandResult.createFrom;
const $$createType8 = $models.PublicAccessCommandResult.createFrom;
const $$createType9 = session$0.SaveResult.createFrom;
