// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";

/**
 * AssignmentPayload assigns one available character to one unassigned
 * logical session.
 */
export class AssignmentPayload {
    /**
     * Creates a new AssignmentPayload instance.
     * @param {Partial<AssignmentPayload>} [$$source = {}] - The source object to create the AssignmentPayload.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {domain$0.LogicalSessionID}
             */
            this["sessionId"] = "";
        }
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {domain$0.CharacterID}
             */
            this["characterId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssignmentPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssignmentPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssignmentPayload(/** @type {Partial<AssignmentPayload>} */($$parsedSource));
    }
}

/**
 * CharacterRenamePayload identifies one stable roster entry and its new
 * player-facing display name.
 */
export class CharacterRenamePayload {
    /**
     * Creates a new CharacterRenamePayload instance.
     * @param {Partial<CharacterRenamePayload>} [$$source = {}] - The source object to create the CharacterRenamePayload.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {domain$0.CharacterID}
             */
            this["characterId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterRenamePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CharacterRenamePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CharacterRenamePayload(/** @type {Partial<CharacterRenamePayload>} */($$parsedSource));
    }
}

/**
 * CommandResult is used for privileged commands that do not return a model.
 */
export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

/**
 * CoordinationCommandResult returns the authoritative detached state for
 * both accepted and rejected roster/broadcast commands.
 */
export class CoordinationCommandResult {
    /**
     * Creates a new CoordinationCommandResult instance.
     * @param {Partial<CoordinationCommandResult>} [$$source = {}] - The source object to create the CoordinationCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoordinationCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CoordinationCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        return new CoordinationCommandResult(/** @type {Partial<CoordinationCommandResult>} */($$parsedSource));
    }
}

/**
 * LiveTerminalPayload is the validated set-live bridge input.
 */
export class LiveTerminalPayload {
    /**
     * Creates a new LiveTerminalPayload instance.
     * @param {Partial<LiveTerminalPayload>} [$$source = {}] - The source object to create the LiveTerminalPayload.
     */
    constructor($$source = {}) {
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }
        if (!("terminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalName"] = "";
        }
        if (!("tree" in $$source)) {
            /**
             * @member
             * @type {domain$0.ContentNode}
             */
            this["tree"] = null;
        }
        if (!("hackLevel" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hackLevel"] = 0;
        }
        if (!("introText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["introText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveTerminalPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LiveTerminalPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveTerminalPayload(/** @type {Partial<LiveTerminalPayload>} */($$parsedSource));
    }
}

/**
 * LiveUpdatePayload replaces published content without resetting a puzzle.
 */
export class LiveUpdatePayload {
    /**
     * Creates a new LiveUpdatePayload instance.
     * @param {Partial<LiveUpdatePayload>} [$$source = {}] - The source object to create the LiveUpdatePayload.
     */
    constructor($$source = {}) {
        if (!("tree" in $$source)) {
            /**
             * @member
             * @type {domain$0.ContentNode}
             */
            this["tree"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["introText"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LiveUpdatePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LiveUpdatePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LiveUpdatePayload(/** @type {Partial<LiveUpdatePayload>} */($$parsedSource));
    }
}

/**
 * LogicalSessionRenamePayload changes only a process-local fallback label.
 */
export class LogicalSessionRenamePayload {
    /**
     * Creates a new LogicalSessionRenamePayload instance.
     * @param {Partial<LogicalSessionRenamePayload>} [$$source = {}] - The source object to create the LogicalSessionRenamePayload.
     */
    constructor($$source = {}) {
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {domain$0.LogicalSessionID}
             */
            this["sessionId"] = "";
        }
        if (!("fallbackName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fallbackName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogicalSessionRenamePayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogicalSessionRenamePayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogicalSessionRenamePayload(/** @type {Partial<LogicalSessionRenamePayload>} */($$parsedSource));
    }
}

/**
 * MoveCharacterPayload atomically transfers one stable character identity.
 */
export class MoveCharacterPayload {
    /**
     * Creates a new MoveCharacterPayload instance.
     * @param {Partial<MoveCharacterPayload>} [$$source = {}] - The source object to create the MoveCharacterPayload.
     */
    constructor($$source = {}) {
        if (!("characterId" in $$source)) {
            /**
             * @member
             * @type {domain$0.CharacterID}
             */
            this["characterId"] = "";
        }
        if (!("toSessionId" in $$source)) {
            /**
             * @member
             * @type {domain$0.LogicalSessionID}
             */
            this["toSessionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveCharacterPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveCharacterPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveCharacterPayload(/** @type {Partial<MoveCharacterPayload>} */($$parsedSource));
    }
}

/**
 * PlayerConfigCommandResult combines durable metadata with authoritative roster state.
 */
export class PlayerConfigCommandResult {
    /**
     * Creates a new PlayerConfigCommandResult instance.
     * @param {Partial<PlayerConfigCommandResult>} [$$source = {}] - The source object to create the PlayerConfigCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("canceled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canceled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.PlayerConfigMetadata | null | undefined}
             */
            this["playerConfig"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.Session | null | undefined}
             */
            this["session"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerConfigCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerConfigCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("playerConfig" in $$parsedSource) {
            $$parsedSource["playerConfig"] = $$createField3_0($$parsedSource["playerConfig"]);
        }
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField5_0($$parsedSource["state"]);
        }
        return new PlayerConfigCommandResult(/** @type {Partial<PlayerConfigCommandResult>} */($$parsedSource));
    }
}

/**
 * RuntimeStatus is the synchronous startup/status snapshot used to avoid
 * losing events emitted before the frontend subscribes.
 */
export class RuntimeStatus {
    /**
     * Creates a new RuntimeStatus instance.
     * @param {Partial<RuntimeStatus>} [$$source = {}] - The source object to create the RuntimeStatus.
     */
    constructor($$source = {}) {
        if (!("serverInfo" in $$source)) {
            /**
             * @member
             * @type {domain$0.ServerInfo | null}
             */
            this["serverInfo"] = null;
        }
        if (!("clientCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["clientCount"] = 0;
        }
        if (!("hackState" in $$source)) {
            /**
             * @member
             * @type {domain$0.PublicHackState | null}
             */
            this["hackState"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startupError"] = undefined;
        }
        if (!("saveState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["saveState"] = "";
        }
        if (!("requestedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestedRevision"] = 0;
        }
        if (!("savedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["savedRevision"] = 0;
        }
        if (!("coordinationState" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["coordinationState"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeStatus}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField2_0 = $$createType7;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serverInfo" in $$parsedSource) {
            $$parsedSource["serverInfo"] = $$createField0_0($$parsedSource["serverInfo"]);
        }
        if ("hackState" in $$parsedSource) {
            $$parsedSource["hackState"] = $$createField2_0($$parsedSource["hackState"]);
        }
        if ("coordinationState" in $$parsedSource) {
            $$parsedSource["coordinationState"] = $$createField7_0($$parsedSource["coordinationState"]);
        }
        return new RuntimeStatus(/** @type {Partial<RuntimeStatus>} */($$parsedSource));
    }
}

/**
 * TerminalSwitchCommandResult describes either a completed terminal selection
 * or a later decision gate. SwitchID remains empty for direct activation and
 * clear operations; unfinished-puzzle choices populate it in the US8 flow.
 */
export class TerminalSwitchCommandResult {
    /**
     * Creates a new TerminalSwitchCommandResult instance.
     * @param {Partial<TerminalSwitchCommandResult>} [$$source = {}] - The source object to create the TerminalSwitchCommandResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.SwitchID | undefined}
             */
            this["switchId"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {domain$0.MasterCoordinationState | null}
             */
            this["state"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSwitchCommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalSwitchCommandResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField4_0($$parsedSource["state"]);
        }
        return new TerminalSwitchCommandResult(/** @type {Partial<TerminalSwitchCommandResult>} */($$parsedSource));
    }
}

/**
 * TerminalSwitchDecisionPayload resolves one opaque unfinished-puzzle switch
 * request with an exact allowlisted decision.
 */
export class TerminalSwitchDecisionPayload {
    /**
     * Creates a new TerminalSwitchDecisionPayload instance.
     * @param {Partial<TerminalSwitchDecisionPayload>} [$$source = {}] - The source object to create the TerminalSwitchDecisionPayload.
     */
    constructor($$source = {}) {
        if (!("switchId" in $$source)) {
            /**
             * @member
             * @type {domain$0.SwitchID}
             */
            this["switchId"] = "";
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {domain$0.TerminalSwitchChoice}
             */
            this["decision"] = domain$0.TerminalSwitchChoice.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalSwitchDecisionPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalSwitchDecisionPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalSwitchDecisionPayload(/** @type {Partial<TerminalSwitchDecisionPayload>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = domain$0.MasterCoordinationState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = domain$0.PlayerConfigMetadata.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = domain$0.ServerInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = domain$0.PublicHackState.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
