#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repository_root}"
export BUF_CACHE_DIR="${BUF_CACHE_DIR:-${TMPDIR:-/tmp}/fallout-terminal-buf-cache}"
export GOCACHE="${GOCACHE:-${TMPDIR:-/tmp}/fallout-terminal-go-cache}"
if [[ "$(go env GOOS)" == darwin ]]; then
  export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-13.0}"
  export CGO_CFLAGS="${CGO_CFLAGS:--mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}}"
  export CGO_LDFLAGS="${CGO_LDFLAGS:--mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET} -Wl,-no_warn_duplicate_libraries}"
fi

temporary="$(mktemp -d "${TMPDIR:-/tmp}/fallout-proto-check.XXXXXX")"
trap 'rm -rf "$temporary"' EXIT HUP INT TERM

generated_manifest() {
  local root="$1"
  local destination="$2"
  (
    cd "$root"
    find internal/gen frontend/client/gen -type f -print \
      | LC_ALL=C sort \
      | while IFS= read -r generated; do
          printf '%s\t%s\n' "$generated" "$(shasum -a 256 "$generated" | awk '{print $1}')"
        done
  ) >"$destination"
}

capture_generated_tree() {
  local destination="$1"
  mkdir -p "$destination/internal" "$destination/frontend/client"
  cp -R internal/gen "$destination/internal/gen"
  cp -R frontend/client/gen "$destination/frontend/client/gen"
}

compare_manifests() {
  local first="$1"
  local second="$2"
  local diagnostic="$3"
  if ! cmp -s "$first" "$second"; then
    diff -u "$first" "$second" >&2 || true
    printf '%s\n' "$diagnostic" >&2
    exit 1
  fi
}

go tool -modfile=tools/buf/go.mod buf format proto --diff --exit-code
go tool -modfile=tools/buf/go.mod buf lint proto
go tool -modfile=tools/buf/go.mod buf build proto >/dev/null

generated_manifest "$repository_root" "$temporary/checked-in.manifest"
scripts/proto-generate.sh
capture_generated_tree "$temporary/first"
generated_manifest "$temporary/first" "$temporary/first.manifest"
compare_manifests "$temporary/checked-in.manifest" "$temporary/first.manifest" \
  'checked-in generated contracts drift from a clean pinned-Buf generation'
scripts/proto-generate.sh
capture_generated_tree "$temporary/second"
generated_manifest "$temporary/second" "$temporary/second.manifest"
compare_manifests "$temporary/first.manifest" "$temporary/second.manifest" \
  'two clean generations produced different artifacts'
second_revision="$(shasum -a 256 "$temporary/second.manifest" | awk '{print $1}')"

if find internal/gen -type f -name '*.go' -print0 | xargs -0 grep -L '^// Code generated by ' | grep -q .; then
  printf 'a generated Go source is missing its generated header\n' >&2
  exit 1
fi
if find internal/gen -type f -name '*.pb.go' -print0 | xargs -0 grep -L -E '^//[[:space:]]+protoc-gen-go v1\.36\.11$' | grep -q .; then
  printf 'generated Go protobuf provenance does not record pinned protoc-gen-go v1.36.11\n' >&2
  exit 1
fi
if find internal/gen -type f -name '*.pb.go' -print0 | xargs -0 grep -L -E '^//[[:space:]]+protoc[[:space:]]+\(unknown\)$' | grep -q .; then
  printf 'generated Go protobuf provenance is not compatible with Buf in-process compilation\n' >&2
  exit 1
fi
generated_dir='frontend/client/gen/fallout/terminal/player/v1'
expected_names="$(printf '%s\n' hacking_pb.ts navigation_pb.ts player_pb.ts sound_pb.ts terminal_pb.ts | LC_ALL=C sort)"
actual_names="$(find "$generated_dir" -maxdepth 1 -type f -exec basename {} \; | LC_ALL=C sort)"
if [[ "$actual_names" != "$expected_names" ]]; then
  printf 'generated browser inventory differs from the exact five TypeScript contracts\nexpected:\n%s\nactual:\n%s\n' \
    "$expected_names" "$actual_names" >&2
  exit 1
fi
for generated in hacking_pb.ts navigation_pb.ts player_pb.ts sound_pb.ts terminal_pb.ts; do
  generated_path="$generated_dir/$generated"
  if [[ ! -r "$generated_path" ]] \
    || ! grep -Fxq '// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=js"' "$generated_path"; then
    printf 'generated browser TypeScript provenance is missing or incorrect: %s\n' "$generated_path" >&2
    exit 1
  fi
done
if find frontend/client/gen -type f \( -name '*.js' -o -name '*_pb.d.ts' \) -print | grep -q .; then
  printf 'stale browser JavaScript or declaration output remains\n' >&2
  exit 1
fi
if ! grep -ERq 'from "\./[^"]+_pb\.js"' "$generated_dir"; then
  printf 'generated browser TypeScript does not retain relative .js import specifiers\n' >&2
  exit 1
fi
if grep -ERn 'from "\./[^"]+_pb\.(ts|d\.ts)"' "$generated_dir"; then
  printf 'generated browser imports bypass the governed .js specifier contract\n' >&2
  exit 1
fi

if [[ -e proto/toolchain.env || -e scripts/ensure-protoc.sh ]]; then
  printf 'standalone protoc distribution metadata remains in the repository\n' >&2
  exit 1
fi
if grep -En 'ensure-protoc\.sh|proto/toolchain\.env|libprotoc 35\.0|protoc v7\.35\.0' scripts/proto-generate.sh; then
  printf 'an active generation or CI path still requires standalone protoc\n' >&2
  exit 1
fi

if grep -ERn 'fallout/terminal/(private|persistence|config)/' proto/fallout/terminal/player frontend/client/gen; then
  printf 'the public descriptor or browser graph imports a non-public contract\n' >&2
  exit 1
fi
if find frontend/client/gen -type f ! -path 'frontend/client/gen/fallout/terminal/player/v1/*' -print | grep -q .; then
  printf 'the browser generated tree contains a non-public package\n' >&2
  exit 1
fi

go test ./internal/player -run '^$'
go test ./internal/session ./internal/playerconfig
go test ./internal/platform -run '^TestProtobuf'
go test . -run '^TestPrivate'
npm run build:client --prefix frontend
if grep -ERn 'fallout\.terminal\.(private|persistence|config)|internal/gen/fallout/terminal/(private|persistence|config)' frontend/client/dist; then
  printf 'the browser bundle contains a private contract reference\n' >&2
  exit 1
fi

printf 'Protobuf contracts are formatted, linted, deterministic, isolated, exhaustive, and buildable (%s).\n' "${second_revision}"

rm -rf "$temporary"
trap - EXIT HUP INT TERM
