#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repository_root}"
export BUF_CACHE_DIR="${BUF_CACHE_DIR:-${TMPDIR:-/tmp}/fallout-terminal-buf-cache}"
export GOCACHE="${GOCACHE:-${TMPDIR:-/tmp}/fallout-terminal-go-cache}"

generated_revision() {
  find internal/gen client/gen -type f -print \
    | LC_ALL=C sort \
    | while IFS= read -r generated; do shasum -a 256 "${generated}"; done \
    | shasum -a 256 \
    | awk '{print $1}'
}

(
  cd proto
  go tool buf format --diff --exit-code
  go tool buf lint
  go tool buf build >/dev/null
)

scripts/proto-generate.sh
first_revision="$(generated_revision)"
scripts/proto-generate.sh
second_revision="$(generated_revision)"
if [[ "${first_revision}" != "${second_revision}" ]]; then
  printf 'two clean generations produced different artifacts\n' >&2
  exit 1
fi

if find internal/gen -type f -name '*.go' -print0 | xargs -0 grep -L '^// Code generated by ' | grep -q .; then
  printf 'a generated Go source is missing its generated header\n' >&2
  exit 1
fi
if find client/gen -type f -name '*.js' -print0 | xargs -0 grep -L '^// @generated by protoc-gen-es ' | grep -q .; then
  printf 'a generated ECMAScript source is missing its generated header\n' >&2
  exit 1
fi

if rg -n 'fallout/terminal/(private|persistence|config)/' proto/fallout/terminal/player client/gen; then
  printf 'the public descriptor or browser graph imports a non-public contract\n' >&2
  exit 1
fi
if find client/gen -type f ! -path 'client/gen/fallout/terminal/player/v1/*' -print | grep -q .; then
  printf 'the browser generated tree contains a non-public package\n' >&2
  exit 1
fi

go test ./internal/player -run '^$'
go test ./internal/session ./internal/playerconfig
go test ./internal/platform -run '^TestProtobuf'
go test . -run '^TestPrivate'
npm run build --prefix client
if rg -n 'fallout\.terminal\.(private|persistence|config)|internal/gen/fallout/terminal/(private|persistence|config)' client/dist; then
  printf 'the browser bundle contains a private contract reference\n' >&2
  exit 1
fi

printf 'Protobuf contracts are formatted, linted, deterministic, isolated, exhaustive, and buildable (%s).\n' "${second_revision}"
