#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repository_root}"
export BUF_CACHE_DIR="${BUF_CACHE_DIR:-${TMPDIR:-/tmp}/fallout-terminal-buf-cache}"
export GOCACHE="${GOCACHE:-${TMPDIR:-/tmp}/fallout-terminal-go-cache}"
if [[ "$(go env GOOS)" == darwin ]]; then
  export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-13.0}"
  export CGO_CFLAGS="${CGO_CFLAGS:--mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}}"
  export CGO_LDFLAGS="${CGO_LDFLAGS:--mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}}"
fi

generated_revision() {
  find internal/gen frontend/client/gen -type f -print \
    | LC_ALL=C sort \
    | while IFS= read -r generated; do shasum -a 256 "${generated}"; done \
    | shasum -a 256 \
    | awk '{print $1}'
}

go tool -modfile=tools/buf/go.mod buf format proto --diff --exit-code
go tool -modfile=tools/buf/go.mod buf lint proto
go tool -modfile=tools/buf/go.mod buf build proto >/dev/null

checked_in_revision="$(generated_revision)"
scripts/proto-generate.sh
first_revision="$(generated_revision)"
if [[ "${checked_in_revision}" != "${first_revision}" ]]; then
  printf 'checked-in generated contracts drift from a clean pinned-Buf generation\n' >&2
  exit 1
fi
scripts/proto-generate.sh
second_revision="$(generated_revision)"
if [[ "${first_revision}" != "${second_revision}" ]]; then
  printf 'two clean generations produced different artifacts\n' >&2
  exit 1
fi

if find internal/gen -type f -name '*.go' -print0 | xargs -0 grep -L '^// Code generated by ' | grep -q .; then
  printf 'a generated Go source is missing its generated header\n' >&2
  exit 1
fi
if find internal/gen -type f -name '*.pb.go' -print0 | xargs -0 grep -L -E '^//[[:space:]]+protoc-gen-go v1\.36\.11$' | grep -q .; then
  printf 'generated Go protobuf provenance does not record pinned protoc-gen-go v1.36.11\n' >&2
  exit 1
fi
if find internal/gen -type f -name '*.pb.go' -print0 | xargs -0 grep -L -E '^//[[:space:]]+protoc[[:space:]]+\(unknown\)$' | grep -q .; then
  printf 'generated Go protobuf provenance is not compatible with Buf in-process compilation\n' >&2
  exit 1
fi
if find frontend/client/gen -type f -name '*.js' -print0 | xargs -0 grep -L '^// @generated by protoc-gen-es v2\.13\.0 ' | grep -q .; then
  printf 'generated ECMAScript provenance does not record pinned protoc-gen-es v2.13.0\n' >&2
  exit 1
fi

if [[ -e proto/toolchain.env || -e scripts/ensure-protoc.sh ]]; then
  printf 'standalone protoc distribution metadata remains in the repository\n' >&2
  exit 1
fi
if grep -En 'ensure-protoc\.sh|proto/toolchain\.env|libprotoc 35\.0|protoc v7\.35\.0' scripts/proto-generate.sh; then
  printf 'an active generation or CI path still requires standalone protoc\n' >&2
  exit 1
fi

if grep -ERn 'fallout/terminal/(private|persistence|config)/' proto/fallout/terminal/player frontend/client/gen; then
  printf 'the public descriptor or browser graph imports a non-public contract\n' >&2
  exit 1
fi
if find frontend/client/gen -type f ! -path 'frontend/client/gen/fallout/terminal/player/v1/*' -print | grep -q .; then
  printf 'the browser generated tree contains a non-public package\n' >&2
  exit 1
fi

go test ./internal/player -run '^$'
go test ./internal/session ./internal/playerconfig
go test ./internal/platform -run '^TestProtobuf'
go test . -run '^TestPrivate'
npm run build:client --prefix frontend
if grep -ERn 'fallout\.terminal\.(private|persistence|config)|internal/gen/fallout/terminal/(private|persistence|config)' frontend/client/dist; then
  printf 'the browser bundle contains a private contract reference\n' >&2
  exit 1
fi

printf 'Protobuf contracts are formatted, linted, deterministic, isolated, exhaustive, and buildable (%s).\n' "${second_revision}"
