// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    CommandApprovalMode,
    CommandExecutionDecision,
    HackColumn,
    HackWord,
    MasterBroadcastState,
    MasterCoordinationState,
    MasterPendingCommandExecution,
    MasterPendingSwitch,
    MasterPendingTerminalNavigation,
    MasterRosterEntry,
    MasterSessionEntry,
    MasterTerminalNavigationNotice,
    PlayerCharacter,
    PlayerConfigMetadata,
    PlayerRole,
    PublicHackPattern,
    PublicHackState,
    ServerInfo,
    TerminalGroup,
    TerminalNavigationDecision,
    TerminalNavigationDirection,
    TerminalNavigationNoticeReason,
    TerminalSwitchChoice
} from "./models.js";

import * as $models from "./models.js";

/**
 * BroadcastID identifies one live-broadcast lifetime.
 * @typedef {$models.BroadcastID} BroadcastID
 */

/**
 * CharacterID identifies one process-local roster entry.
 * @typedef {$models.CharacterID} CharacterID
 */

/**
 * ContentNode is a tagged folder, command, or entry node.
 * @typedef {$models.ContentNode} ContentNode
 */

/**
 * LogicalSessionID identifies one browser profile for the lifetime of a server process.
 * @typedef {$models.LogicalSessionID} LogicalSessionID
 */

/**
 * Session is the durable version-1 campaign document.
 * @typedef {$models.Session} Session
 */

/**
 * SwitchID identifies one pending terminal-switch decision.
 * @typedef {$models.SwitchID} SwitchID
 */
