// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BroadcastID identifies one live-broadcast lifetime.
 * @typedef {string} BroadcastID
 */

/**
 * CharacterID identifies one process-local roster entry.
 * @typedef {string} CharacterID
 */

/**
 * CommandApprovalMode records the exact behavior that will run after the
 * Overseer approves a pending command. Completed state-changing commands
 * remain distinct because approval must show their frozen result without a
 * second durable write.
 * @readonly
 * @enum {string}
 */
export const CommandApprovalMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CommandApprovalModeOrdinary: "ordinary",
    CommandApprovalModeStateChange: "state-change",
    CommandApprovalModeCompletedStateChange: "completed-state-change",
};

/**
 * CommandExecutionDecision is the trusted Overseer resolution for the
 * exact currently pending state-changing command request.
 * @readonly
 * @enum {string}
 */
export const CommandExecutionDecision = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    CommandExecutionApprove: "approve",
    CommandExecutionReject: "reject",
};

/**
 * ContentNode is a tagged folder, command, or entry node.
 * @typedef {any} ContentNode
 */

/**
 * HackColumn is one 192-character public hacking column.
 */
export class HackColumn {
    /**
     * Creates a new HackColumn instance.
     * @param {Partial<HackColumn>} [$$source = {}] - The source object to create the HackColumn.
     */
    constructor($$source = {}) {
        if (!("addresses" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["addresses"] = [];
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("words" in $$source)) {
            /**
             * @member
             * @type {HackWord[]}
             */
            this["words"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HackColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HackColumn}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addresses" in $$parsedSource) {
            $$parsedSource["addresses"] = $$createField0_0($$parsedSource["addresses"]);
        }
        if ("words" in $$parsedSource) {
            $$parsedSource["words"] = $$createField2_0($$parsedSource["words"]);
        }
        return new HackColumn(/** @type {Partial<HackColumn>} */($$parsedSource));
    }
}

/**
 * HackWord describes a visible word placement in a hacking column.
 */
export class HackWord {
    /**
     * Creates a new HackWord instance.
     * @param {Partial<HackWord>} [$$source = {}] - The source object to create the HackWord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("length" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["length"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HackWord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HackWord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HackWord(/** @type {Partial<HackWord>} */($$parsedSource));
    }
}

/**
 * LogicalSessionID identifies one browser profile for the lifetime of a server process.
 * @typedef {string} LogicalSessionID
 */

/**
 * MasterBroadcastState is the Overseer view of the current broadcast epoch.
 */
export class MasterBroadcastState {
    /**
     * Creates a new MasterBroadcastState instance.
     * @param {Partial<MasterBroadcastState>} [$$source = {}] - The source object to create the MasterBroadcastState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["id"] = "";
        }
        if (!("controllerSessionId" in $$source)) {
            /**
             * @member
             * @type {LogicalSessionID | null}
             */
            this["controllerSessionId"] = null;
        }
        if (!("activeTerminalId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["activeTerminalId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterBroadcastState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterBroadcastState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterBroadcastState(/** @type {Partial<MasterBroadcastState>} */($$parsedSource));
    }
}

/**
 * MasterCoordinationState is one detached private-desktop projection.
 */
export class MasterCoordinationState {
    /**
     * Creates a new MasterCoordinationState instance.
     * @param {Partial<MasterCoordinationState>} [$$source = {}] - The source object to create the MasterCoordinationState.
     */
    constructor($$source = {}) {
        if (!("revision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["revision"] = 0;
        }
        if (!("playerConfig" in $$source)) {
            /**
             * @member
             * @type {PlayerConfigMetadata | null}
             */
            this["playerConfig"] = null;
        }
        if (!("roster" in $$source)) {
            /**
             * @member
             * @type {MasterRosterEntry[]}
             */
            this["roster"] = [];
        }
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {MasterSessionEntry[]}
             */
            this["sessions"] = [];
        }
        if (!("broadcast" in $$source)) {
            /**
             * @member
             * @type {MasterBroadcastState | null}
             */
            this["broadcast"] = null;
        }
        if (!("pendingSwitch" in $$source)) {
            /**
             * @member
             * @type {MasterPendingSwitch | null}
             */
            this["pendingSwitch"] = null;
        }
        if (!("pendingCommandExecution" in $$source)) {
            /**
             * @member
             * @type {MasterPendingCommandExecution | null}
             */
            this["pendingCommandExecution"] = null;
        }
        if (!("pendingTerminalNavigation" in $$source)) {
            /**
             * @member
             * @type {MasterPendingTerminalNavigation | null}
             */
            this["pendingTerminalNavigation"] = null;
        }
        if (!("terminalNavigationNotice" in $$source)) {
            /**
             * @member
             * @type {MasterTerminalNavigationNotice | null}
             */
            this["terminalNavigationNotice"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterCoordinationState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterCoordinationState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType12;
        const $$createField6_0 = $$createType14;
        const $$createField7_0 = $$createType16;
        const $$createField8_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("playerConfig" in $$parsedSource) {
            $$parsedSource["playerConfig"] = $$createField1_0($$parsedSource["playerConfig"]);
        }
        if ("roster" in $$parsedSource) {
            $$parsedSource["roster"] = $$createField2_0($$parsedSource["roster"]);
        }
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField3_0($$parsedSource["sessions"]);
        }
        if ("broadcast" in $$parsedSource) {
            $$parsedSource["broadcast"] = $$createField4_0($$parsedSource["broadcast"]);
        }
        if ("pendingSwitch" in $$parsedSource) {
            $$parsedSource["pendingSwitch"] = $$createField5_0($$parsedSource["pendingSwitch"]);
        }
        if ("pendingCommandExecution" in $$parsedSource) {
            $$parsedSource["pendingCommandExecution"] = $$createField6_0($$parsedSource["pendingCommandExecution"]);
        }
        if ("pendingTerminalNavigation" in $$parsedSource) {
            $$parsedSource["pendingTerminalNavigation"] = $$createField7_0($$parsedSource["pendingTerminalNavigation"]);
        }
        if ("terminalNavigationNotice" in $$parsedSource) {
            $$parsedSource["terminalNavigationNotice"] = $$createField8_0($$parsedSource["terminalNavigationNotice"]);
        }
        return new MasterCoordinationState(/** @type {Partial<MasterCoordinationState>} */($$parsedSource));
    }
}

/**
 * MasterPendingCommandExecution is the complete private prompt projection.
 */
export class MasterPendingCommandExecution {
    /**
     * Creates a new MasterPendingCommandExecution instance.
     * @param {Partial<MasterPendingCommandExecution>} [$$source = {}] - The source object to create the MasterPendingCommandExecution.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("broadcastId" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["broadcastId"] = "";
        }
        if (!("terminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["terminalId"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }
        if (!("commandName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandName"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {CommandApprovalMode}
             */
            this["mode"] = CommandApprovalMode.$zero;
        }
        if (!("confirmationText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["confirmationText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterPendingCommandExecution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterPendingCommandExecution}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterPendingCommandExecution(/** @type {Partial<MasterPendingCommandExecution>} */($$parsedSource));
    }
}

/**
 * MasterPendingSwitch is the non-secret metadata for one pending switch decision.
 */
export class MasterPendingSwitch {
    /**
     * Creates a new MasterPendingSwitch instance.
     * @param {Partial<MasterPendingSwitch>} [$$source = {}] - The source object to create the MasterPendingSwitch.
     */
    constructor($$source = {}) {
        if (!("switchId" in $$source)) {
            /**
             * @member
             * @type {SwitchID}
             */
            this["switchId"] = "";
        }
        if (!("broadcastId" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["broadcastId"] = "";
        }
        if (!("sourceTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalId"] = "";
        }
        if (!("targetTerminalId" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["targetTerminalId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterPendingSwitch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterPendingSwitch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterPendingSwitch(/** @type {Partial<MasterPendingSwitch>} */($$parsedSource));
    }
}

export class MasterPendingTerminalNavigation {
    /**
     * Creates a new MasterPendingTerminalNavigation instance.
     * @param {Partial<MasterPendingTerminalNavigation>} [$$source = {}] - The source object to create the MasterPendingTerminalNavigation.
     */
    constructor($$source = {}) {
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("broadcastId" in $$source)) {
            /**
             * @member
             * @type {BroadcastID}
             */
            this["broadcastId"] = "";
        }
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {TerminalNavigationDirection}
             */
            this["direction"] = TerminalNavigationDirection.$zero;
        }
        if (!("sourceTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalId"] = "";
        }
        if (!("sourceTerminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalName"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }
        if (!("commandName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandName"] = "";
        }
        if (!("targetTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetTerminalId"] = "";
        }
        if (!("targetTerminalName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetTerminalName"] = "";
        }
        if (!("routeDepth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["routeDepth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterPendingTerminalNavigation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterPendingTerminalNavigation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterPendingTerminalNavigation(/** @type {Partial<MasterPendingTerminalNavigation>} */($$parsedSource));
    }
}

/**
 * MasterRosterEntry is the Overseer view of one roster claim.
 */
export class MasterRosterEntry {
    /**
     * Creates a new MasterRosterEntry instance.
     * @param {Partial<MasterRosterEntry>} [$$source = {}] - The source object to create the MasterRosterEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {CharacterID}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("intelligence" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["intelligence"] = 0;
        }
        if (!("hackerPerkAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hackerPerkAvailable"] = false;
        }
        if (!("claimedBySessionId" in $$source)) {
            /**
             * @member
             * @type {LogicalSessionID | null}
             */
            this["claimedBySessionId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterRosterEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterRosterEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterRosterEntry(/** @type {Partial<MasterRosterEntry>} */($$parsedSource));
    }
}

/**
 * MasterSessionEntry is the Overseer view of one recognized logical session.
 */
export class MasterSessionEntry {
    /**
     * Creates a new MasterSessionEntry instance.
     * @param {Partial<MasterSessionEntry>} [$$source = {}] - The source object to create the MasterSessionEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {LogicalSessionID}
             */
            this["id"] = "";
        }
        if (!("fallbackName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fallbackName"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("character" in $$source)) {
            /**
             * @member
             * @type {PlayerCharacter | null}
             */
            this["character"] = null;
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {PlayerRole}
             */
            this["role"] = PlayerRole.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterSessionEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterSessionEntry}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("character" in $$parsedSource) {
            $$parsedSource["character"] = $$createField3_0($$parsedSource["character"]);
        }
        return new MasterSessionEntry(/** @type {Partial<MasterSessionEntry>} */($$parsedSource));
    }
}

export class MasterTerminalNavigationNotice {
    /**
     * Creates a new MasterTerminalNavigationNotice instance.
     * @param {Partial<MasterTerminalNavigationNotice>} [$$source = {}] - The source object to create the MasterTerminalNavigationNotice.
     */
    constructor($$source = {}) {
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {TerminalNavigationNoticeReason}
             */
            this["reason"] = TerminalNavigationNoticeReason.$zero;
        }
        if (!("sourceTerminalId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceTerminalId"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["targetTerminalId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterTerminalNavigationNotice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MasterTerminalNavigationNotice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterTerminalNavigationNotice(/** @type {Partial<MasterTerminalNavigationNotice>} */($$parsedSource));
    }
}

/**
 * PlayerCharacter is the assigned identity visible at a projection boundary.
 */
export class PlayerCharacter {
    /**
     * Creates a new PlayerCharacter instance.
     * @param {Partial<PlayerCharacter>} [$$source = {}] - The source object to create the PlayerCharacter.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {CharacterID}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerCharacter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerCharacter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerCharacter(/** @type {Partial<PlayerCharacter>} */($$parsedSource));
    }
}

/**
 * PlayerConfigMetadata is the detached Overseer view of the active config.
 */
export class PlayerConfigMetadata {
    /**
     * Creates a new PlayerConfigMetadata instance.
     * @param {Partial<PlayerConfigMetadata>} [$$source = {}] - The source object to create the PlayerConfigMetadata.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerConfigMetadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerConfigMetadata}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlayerConfigMetadata(/** @type {Partial<PlayerConfigMetadata>} */($$parsedSource));
    }
}

/**
 * PlayerRole is a logical session's current broadcast-wide authority.
 * @readonly
 * @enum {string}
 */
export const PlayerRole = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PlayerRoleUnassigned: "unassigned",
    PlayerRoleActive: "active",
    PlayerRoleObserver: "observer",
};

/**
 * PublicHackPattern is the client-safe projection of one current bracket span.
 */
export class PublicHackPattern {
    /**
     * Creates a new PublicHackPattern instance.
     * @param {Partial<PublicHackPattern>} [$$source = {}] - The source object to create the PublicHackPattern.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("row" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["row"] = 0;
        }
        if (!("start" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["end"] = 0;
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["used"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicHackPattern instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicHackPattern}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicHackPattern(/** @type {Partial<PublicHackPattern>} */($$parsedSource));
    }
}

/**
 * PublicHackState is the only hacking representation permitted at a client boundary.
 */
export class PublicHackState {
    /**
     * Creates a new PublicHackState instance.
     * @param {Partial<PublicHackState>} [$$source = {}] - The source object to create the PublicHackState.
     */
    constructor($$source = {}) {
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["level"] = 0;
        }
        if (!("wordLength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["wordLength"] = 0;
        }
        if (!("attemptsMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attemptsMax"] = 0;
        }
        if (!("attemptsLeft" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attemptsLeft"] = 0;
        }
        if (!("solved" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["solved"] = false;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["failed"] = false;
        }
        if (!("log" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["log"] = [];
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {HackColumn[]}
             */
            this["columns"] = [];
        }
        if (!("patterns" in $$source)) {
            /**
             * @member
             * @type {PublicHackPattern[]}
             */
            this["patterns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicHackState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicHackState}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType22;
        const $$createField8_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("log" in $$parsedSource) {
            $$parsedSource["log"] = $$createField6_0($$parsedSource["log"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField7_0($$parsedSource["columns"]);
        }
        if ("patterns" in $$parsedSource) {
            $$parsedSource["patterns"] = $$createField8_0($$parsedSource["patterns"]);
        }
        return new PublicHackState(/** @type {Partial<PublicHackState>} */($$parsedSource));
    }
}

/**
 * ServerInfo is safe status displayed to the Overseer.
 */
export class ServerInfo {
    /**
     * Creates a new ServerInfo instance.
     * @param {Partial<ServerInfo>} [$$source = {}] - The source object to create the ServerInfo.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["localUrl"] = undefined;
        }
        if (!("tunnel" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tunnel"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["tunnelError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerInfo(/** @type {Partial<ServerInfo>} */($$parsedSource));
    }
}

/**
 * Session is the durable version-1 campaign document.
 * @typedef {any} Session
 */

/**
 * SwitchID identifies one pending terminal-switch decision.
 * @typedef {string} SwitchID
 */

/**
 * TerminalGroup is the durable high-level representation of one ordered set
 * of terminals. A standalone terminal is represented by a one-member group.
 */
export class TerminalGroup {
    /**
     * Creates a new TerminalGroup instance.
     * @param {Partial<TerminalGroup>} [$$source = {}] - The source object to create the TerminalGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("terminalIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["terminalIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("terminalIds" in $$parsedSource) {
            $$parsedSource["terminalIds"] = $$createField2_0($$parsedSource["terminalIds"]);
        }
        return new TerminalGroup(/** @type {Partial<TerminalGroup>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TerminalNavigationDecision = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalNavigationApprove: "approve",
    TerminalNavigationReject: "reject",
};

/**
 * TerminalNavigationDirection distinguishes forward links from LIFO returns.
 * @readonly
 * @enum {string}
 */
export const TerminalNavigationDirection = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalNavigationForward: "forward",
    TerminalNavigationReturn: "return",
};

/**
 * TerminalNavigationNoticeReason is a safe private failure category.
 * @readonly
 * @enum {string}
 */
export const TerminalNavigationNoticeReason = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalNavigationNoticeTargetMissing: "target-missing",
    TerminalNavigationNoticeSelfTarget: "self-target",
    TerminalNavigationNoticeCommandStale: "command-stale",
    TerminalNavigationNoticeTargetChanged: "target-changed",
};

/**
 * TerminalSwitchChoice is the Overseer's explicit unfinished-puzzle decision.
 * @readonly
 * @enum {string}
 */
export const TerminalSwitchChoice = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TerminalSwitchPreserve: "preserve",
    TerminalSwitchDiscard: "discard",
    TerminalSwitchCancel: "cancel",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = HackWord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PlayerConfigMetadata.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = MasterRosterEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = MasterSessionEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = MasterBroadcastState.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = MasterPendingSwitch.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = MasterPendingCommandExecution.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = MasterPendingTerminalNavigation.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = MasterTerminalNavigationNotice.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = PlayerCharacter.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = HackColumn.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = PublicHackPattern.createFrom;
const $$createType24 = $Create.Array($$createType23);
