// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * SaveResult reports both the caller's revision and the newest revision known
 * to be durable when that caller completes.
 */
export class SaveResult {
    /**
     * Creates a new SaveResult instance.
     * @param {Partial<SaveResult>} [$$source = {}] - The source object to create the SaveResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("requestedRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requestedRevision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["savedRevision"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveResult(/** @type {Partial<SaveResult>} */($$parsedSource));
    }
}

/**
 * SessionResult is returned by create, open, and demo-copy commands.
 */
export class SessionResult {
    /**
     * Creates a new SessionResult instance.
     * @param {Partial<SessionResult>} [$$source = {}] - The source object to create the SessionResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("canceled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canceled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["filePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.Session | null | undefined}
             */
            this["session"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionResult(/** @type {Partial<SessionResult>} */($$parsedSource));
    }
}
